In [2]:
# Importação das bibliotecas necessárias
import pandas as pd
import numpy as np
import psycopg2
import math
from datetime import datetime
import sys
import os
import openpyxl
import boto3
from io import BytesIO
from sqlalchemy import create_engine

In [4]:
pd.set_option("display.max_columns", None)

In [32]:
nome_empresa = input("Digite o nome da empresa: ")

if nome_empresa.lower() == 'tateti':
    cnpj = "65369985000504"
    cnpj_produtos = "65369985000334"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'ladakh':
    cnpj = "07318052000150"
    cnpj_produtos = "07318052000150"
    cnpjs = [cnpj]

if nome_empresa.lower() == 'sonda':
    cnpj = "01937635001316"
    cnpj_produtos = "01937635001316"
    cnpjs = [cnpj]

engine = create_engine(
    f"postgresql+psycopg2://cat:5pM2h0MBQu9JHkxHud2A@177.11.49.194:3361/4btaxtech"
)

# Variáveis para acesso ao s3
bucket_name = '4btaxtech'

s3 = boto3.client('s3', 
                  aws_access_key_id='AKIA4RCAOBRSFONXEUTE', 
                  aws_secret_access_key='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',
                  region_name='us-east-1'
                  )

print("✅ Cliente S3 autenticado com sucesso!")

Digite o nome da empresa:  sonda

✅ Cliente S3 autenticado com sucesso!

In [8]:
def ler_arquivo_para_dataframe(bucket_name, s3_key, file_type='csv', sep=None):
    """
    Lê um arquivo do S3 e carrega em um DataFrame do Pandas.
    
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho do arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    :return: DataFrame do Pandas.
    """
    try:
        response = s3.get_object(Bucket=bucket_name, Key=s3_key)
        if file_type == 'csv':
            df = pd.read_csv(BytesIO(response['Body'].read()), dtype=str, header=0, sep=sep)
        elif file_type == 'xlsx':
            df = pd.read_excel(BytesIO(response['Body'].read()))
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        print(f"Arquivo '{s3_key}' lido com sucesso!")
        return df
    except Exception as e:
        print(f"Erro ao ler arquivo do S3: {e}")
        return None
    
def salvar_dataframe_no_s3(df, bucket_name, s3_key, file_type='csv'):
    """
    Salva um DataFrame do Pandas no S3.
    
    :param df: DataFrame a ser salvo.
    :param bucket_name: Nome do bucket.
    :param s3_key: Caminho para salvar o arquivo no S3.
    :param file_type: Tipo do arquivo ('csv' ou 'xlsx').
    """
    try:
        buffer = BytesIO()
        if file_type == 'csv':
            df.to_csv(buffer, index=False, encoding='utf-8')
        elif file_type == 'xlsx':
            with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
                df.to_excel(writer, index=False)
        else:
            raise ValueError("Tipo de arquivo não suportado. Use 'csv' ou 'xlsx'.")
        
        buffer.seek(0)  # Resetar o ponteiro do buffer
        s3.put_object(Bucket=bucket_name, Key=s3_key, Body=buffer.getvalue())
        print(f"Arquivo salvo com sucesso em '{s3_key}'.")
    except Exception as e:
        print(f"Erro ao salvar arquivo no S3: {e}")

In [14]:
def baixar_arquivo(bucket_name, s3_key, local_file_name):
    try:
        s3.download_file(bucket_name, s3_key, local_file_name)
        print(f"Arquivo '{s3_key}' baixado como '{local_file_name}'.")
    except Exception as e:
        print(f"Erro ao baixar arquivo: {e}")

baixar_arquivo(bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
               local_file_name=f'ficha_3_{nome_empresa}_{cnpj}_v2.xlsx')

Arquivo 'Cat42/Ladakh/Ficha 3/ficha_3_Ladakh_07318052000150_v2.xlsx' baixado como 'ficha_3_ladakh_07318052000150_v2.xlsx'.

In [113]:
colunas = ['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']

ficha_3_revizia = pd.DataFrame(columns=colunas)
teste = ler_arquivo_para_dataframe(bucket_name=bucket_name, s3_key=f'Cat42/{nome_empresa.title()}/Ficha 3/ficha_3_{nome_empresa.title()}_{cnpj}_v2.xlsx',
                                  file_type='xlsx')

Arquivo 'Cat42/Tateti/Ficha 3/ficha_3_Tateti_65369985000504_v2.xlsx' lido com sucesso!

In [114]:
teste['VLR_RESSARCIMENTO'].sum()

np.float64(1177275.8649994466)

In [115]:
ficha_3_revizia['Código da Mercadoria'] = teste['COD_ITEM']
ficha_3_revizia['Número da Ordem'] = teste.groupby('COD_ITEM').cumcount() + 1
ficha_3_revizia['Data'] = teste['DATA']
ficha_3_revizia['Chave'] = teste['CHV_DOC']
ficha_3_revizia['Tipo'] = teste['IND_OPER']
ficha_3_revizia['Código do Remetente ou Destinatário'] = teste['CHV_DOC'].str.slice(6, 20)
ficha_3_revizia['CFOP'] = teste['CFOP']
ficha_3_revizia['Série do documento'] = ficha_3_revizia['Chave'].str.slice(22, 25)
ficha_3_revizia['Número da nota'] = ficha_3_revizia['Chave'].str.slice(25,34)
ficha_3_revizia['Número do Item no Documento XML'] = teste['NUM_ITEM']
ficha_3_revizia['Quantidade (Entrada)'] = np.where(teste['IND_OPER'] == 0, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Total do ICMS Suportado na Retenção ou Antecipação por ST'] = teste['ICMS_TOT']
ficha_3_revizia['Quantidade (Saída)'] = np.where(teste['IND_OPER'] == 1, teste['QTD_CAT'], np.nan)
ficha_3_revizia['Valor Unitário do ICMS Suportado'] = teste['ICMS_SAIDA_UNI']
ficha_3_revizia['Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1'] = np.where(teste['COD_LEGAL'] == 1,
                                                                                                   teste['ICMS_SAIDA'],
                                                                                                   np.nan)
ficha_3_revizia['Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0'] = np.where(teste['COD_LEGAL'] == 0,
                                                                                                                     teste['ICMS_SAIDA'],
                                                                                                                     np.nan)
ficha_3_revizia['Fato Gerador Não Realizado - Código Enquadramento Legal = 2'] = np.where(teste['COD_LEGAL'] == 2,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3'] = np.where(teste['COD_LEGAL'] == 3,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['Saída para Outro Estado - Código Enquadramento Legal = 4'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                          teste['ICMS_SAIDA'],
                                                                                          np.nan)
ficha_3_revizia['ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência'] = teste['VLR_CONF_0']
ficha_3_revizia['Quantidade'] = teste['QTD_SALDO']
ficha_3_revizia['Valor Total do Saldo']  = teste['ICMS_TOT_SALDO']
ficha_3_revizia['Valor Unitário do Saldo'] = ficha_3_revizia['Valor Total do Saldo'] / ficha_3_revizia['Quantidade']
ficha_3_revizia['Valor do Ressarcimento'] = teste['VLR_RESSARCIMENTO']
ficha_3_revizia['Valor do Complemento'] = teste['VLR_COMPLEMENTO']
ficha_3_revizia['ICMS Efetivo da Entrada'] = np.where(teste['COD_LEGAL'].isin([2, 3, 4]), 
                                                      teste['ICMS_EFETIVO_ENTRADA'],
                                                      np.nan)
ficha_3_revizia['ICMS - Crédito da Operação Própria (artigo 271 do RICMS)'] = np.where(teste['COD_LEGAL'] == 4,
                                                                                       teste['ICMS_EFETIVO_ENTRADA'],
                                                                                       np.nan)

# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
ficha_3_revizia[['Série do documento', 'Número da nota']] = ficha_3_revizia['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Função para inserir a linha "cabeçalho" antes das linhas do grupo
def inserir_linha_inicial(grupo):
    # Identificar o código da mercadoria (COD_ITEM) do grupo atual
    cod_item = grupo['Código da Mercadoria'].iloc[0]
    
    # Buscar a primeira linha correspondente no 'teste'
    # (assumindo que todo cod_item de ficha_3_revizia está presente em teste)
    row_teste = teste.loc[teste['COD_ITEM'] == cod_item].iloc[0]

    # Montar o dicionário da nova linha, com colunas específicas
    nova_linha = {
        'Código da Mercadoria': cod_item,
        'Quantidade': row_teste['QTD_INI'],
        'Valor Unitário do Saldo': row_teste['ULT_ICMS_SAIDA_UNI'],
        'Valor Total do Saldo': row_teste['ICMS_INI'],
        # Se quiser deixar as demais colunas em branco (NaN) ou algum valor fixo
        # 'Outra Coluna': '',
        # ...
    }
    
    # Converter a nova linha em um DataFrame de uma única linha
    nova_linha_df = pd.DataFrame([nova_linha])
    
    # Concatenar a nova linha ao grupo (colocando a nova linha antes)
    return pd.concat([nova_linha_df, grupo], ignore_index=True)

# Agrupar por 'Código da Mercadoria' e aplicar a função
ficha_3_revizia_com_cabecalho = (
    ficha_3_revizia
    .groupby('Código da Mercadoria', group_keys=False)
    .apply(inserir_linha_inicial)
)

ficha_3_revizia_com_cabecalho = ficha_3_revizia_com_cabecalho[['Código da Mercadoria', 'Número da Ordem', 'Data', 'Chave', 'Tipo', 'Série do documento', 'Número da nota',
            'Código do Remetente ou Destinatário', 'CFOP', 'Número do Item no Documento XML', 'Quantidade (Entrada)',
            'Valor Total do ICMS Suportado na Retenção ou Antecipação por ST', 'Quantidade (Saída)',
            'Valor Unitário do ICMS Suportado', 'Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1',
            'Fato Gerador Não Realizado - Código Enquadramento Legal = 2', 
            'Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3',
            'Saída para Outro Estado - Código Enquadramento Legal = 4',
            'Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0',
            'ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência',
            'Quantidade',  'Valor Unitário do Saldo', 'Valor Total do Saldo', 'Valor do Ressarcimento', 'Valor do Complemento',
            'ICMS Efetivo da Entrada', 'ICMS - Crédito da Operação Própria (artigo 271 do RICMS)']]


ficha_3_revizia_com_cabecalho

C:\Users\vinic\AppData\Local\Temp\ipykernel_2116\1347571090.py:94: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(inserir_linha_inicial)

,Código da Mercadoria,Número da Ordem,Data,Chave,Tipo,Série do documento,Número da nota,Código do Remetente ou Destinatário,CFOP,Número do Item no Documento XML,Quantidade (Entrada),Valor Total do ICMS Suportado na Retenção ou Antecipação por ST,Quantidade (Saída),Valor Unitário do ICMS Suportado,Saída a Consumidor ou Usuário Final - Código Enquadramento Legal = 1,Fato Gerador Não Realizado - Código Enquadramento Legal = 2,Saída ou Saída Subsequente com isenção ou Não incidência - Código Enquadramento Legal = 3,Saída para Outro Estado - Código Enquadramento Legal = 4,Saída para Comercialização Subsequente(Demais Saídas) - Código Enquadramento Legal = 0,ICMS Efetivo na Saída a Consumidor ou Usuário Final ou no caso de Saída Subsequente com Isenção ou Não Incidência,Quantidade,Valor Unitário do Saldo,Valor Total do Saldo,Valor do Ressarcimento,Valor do Complemento,ICMS Efetivo da Entrada,ICMS - Crédito da Operação Própria (artigo 271 do RICMS)
0,001010101002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,133.83,1.249722,167.250357,NaN,NaN,NaN,NaN
1,001010101002,1.0,2020-03-16,35200365369985000504550060000473171100175734,1.0,006,000047317,65369985000504,5405.0,3.0,NaN,NaN,8.0,1.249722,NaN,NaN,NaN,NaN,9.997780,17.1216,125.83,1.249722,157.252577,0.0,7.123820,NaN,NaN
2,001010101002,2.0,2020-03-18,35200365369985000504550060000473911100009840,1.0,006,000047391,65369985000504,5405.0,1.0,NaN,NaN,3.0,1.249722,NaN,NaN,NaN,NaN,3.749167,8.1432,122.83,1.249722,153.503410,0.0,4.394033,NaN,NaN
3,001010101002,3.0,2020-04-24,35200465369985000504550060000483591100304419,1.0,006,000048359,65369985000504,5405.0,8.0,NaN,NaN,50.0,1.249722,NaN,NaN,NaN,NaN,62.486123,135.7200,72.83,1.249722,91.017287,0.0,73.233877,NaN,NaN
4,001010101002,4.0,2020-05-06,35200565369985000504550060000486951100123356,1.0,006,000048695,65369985000504,5405.0,19.0,NaN,NaN,10.0,1.249722,NaN,NaN,NaN,NaN,12.497225,32.5800,62.83,1.249722,78.520062,0.0,20.082775,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,VIAVE3001005,3.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,1.00,0.402332,0.402332,0.0,0.000000,NaN,NaN
4,VIAVE3001005,4.0,2020-10-23,35201065369985000504590003340440078578021018,1.0,000334044,007857,65369985000504,5102.0,2.0,NaN,NaN,1.0,0.402332,NaN,NaN,NaN,NaN,0.402332,1.6788,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN
0,VIAVE3001006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.00,0.201022,0.402044,NaN,NaN,NaN,NaN
1,VIAVE3001006,1.0,2020-06-18,35200665369985000504590003340440044091519950,1.0,000334044,004409,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,1.00,0.201022,0.201022,0.0,0.000000,NaN,NaN
2,VIAVE3001006,2.0,2020-06-26,35200665369985000504590003340440046248265500,1.0,000334044,004624,65369985000504,5102.0,1.0,NaN,NaN,1.0,0.201022,NaN,NaN,NaN,NaN,0.201022,0.8388,0.00,NaN,0.000000,0.0,0.000000,NaN,NaN

In [116]:
salvar_dataframe_no_s3(ficha_3_revizia_com_cabecalho,
                    bucket_name,
                    f'Cat42/{nome_empresa.title()}/Ficha 3 Revizia/ficha_3_modelo_revizia_{nome_empresa.title()}_{cnpj}.xlsx',
                                                           file_type='xlsx')

Arquivo salvo com sucesso em 'Cat42/Tateti/Ficha 3 Revizia/ficha_3_modelo_revizia_Tateti_65369985000504.xlsx'.

In [6]:
sum(teste['VLR_RESSARCIMENTO'])

2700214.5340872207

In [ ]:
import pandas as pd

# Caminho do arquivo Excel
caminho_arquivo = r"C:\Users\simas\OneDrive\Área de Trabalho\teste.xlsx"

# Carregar a planilha
df = pd.read_excel(caminho_arquivo, dtype=str)


# Função para extrair os dados de acordo com o modelo da chave
def extrair_dados(chave):
    if isinstance(chave, str) and len(chave) == 44:  # Verifica se a chave tem 44 caracteres
        modelo = chave[20:22]  # Posições 21 e 22 determinam o modelo

        if modelo == "55":  # Modelo 55 (NF-e)
            serie = chave[22:25]  # Posições 23 a 25 (3 caracteres)
            numero_nota = chave[25:34]  # Posições 26 a 34 (9 caracteres)
        elif modelo == "59":  # Modelo 59 (CFe-SAT)
            serie = chave[22:31]  # Posições 23 a 31 (9 caracteres - Número de Série do SAT)
            numero_nota = chave[31:37]  # Posições 32 a 37 (6 caracteres - Número do CFe-SAT)
        else:
            serie, numero_nota = None, None  # Caso seja um modelo diferente

        return serie, numero_nota
    return None, None


# Aplicar a função em todas as chaves e preencher as colunas
df[['Série do documento', 'Número da nota']] = df['Chave'].apply(lambda x: pd.Series(extrair_dados(x)))

# Salvar a planilha atualizada
caminho_saida = r"C:\Users\simas\OneDrive\Área de Trabalho\teste_atualizado.xlsx"
df.to_excel(caminho_saida, index=False)

print(f"Arquivo atualizado salvo em: {caminho_saida}")

In [20]:
tabela_1 = ler_arquivo_para_dataframe(bucket_name, f'Cat42/{nome_empresa.title()}/Tabela 1/tabela_1_{nome_empresa}.csv', file_type='csv', sep=';')
# tabela_1 = tabela_1.dropna(subset='Número Item')
# tabela_1[tabela_1['Chave Acesso NFe'] == '35200748155592000147550010000054811002630880']
tabela_1

Arquivo 'Cat42/Sonda/Tabela 1/tabela_1_sonda.csv' lido com sucesso!

,Número Item,Código Produto ou Serviço,CFOP,Quantidade Comercial,Valor Produto ou Serviço,Descrição Produto,Unidade Comercial,Código GTIN,Código NCM,CEST,Valor ICMS Operação,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base de Cálculo ICMS ST Retido,Valor ICMS Substituto,Valor ICMS ST Retido,Valor Total NFE do Produto,Valor Desconto Incondicional,CST ICMS,Tipo,Chave Acesso NFe,Data Emissão,Número CNPJ Emitente,Número CNPJ Destinatário,Valor Total IPI,Código CEST,Valor Base Cálculo ICMS ST Retido Operação Anterior,Valor Unitário Comercial,Valor Unitário Tributação,Quantidade Tributável,Valor Outras Despesas Acessórias,Valor Dedução,Valor Desconto Condicional,Descrição Produto (original),Valor Icms Efet,Código CEST (char),Valor Total Tributo,Valor ICMS ST Retido Operação Anterior
0,1,00341,6105,5.0000,210.00,AGUA DE COCO 300ML CX12 SUDESTE,CX,7898681940042,20098921,1701100,25.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00,entrada,24201204983035000300550010001454351518005129,2020-12-22T00:00:00-03:00,04983035000300,01937635001316,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,00225,6105,5.0000,270.00,AGUA DE COCO 1 LITRO CX C6 SUDESTE,CX,7898681940059,20098921,1701100,32.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00,entrada,24201204983035000300550010001454351518005129,2020-12-22T00:00:00-03:00,04983035000300,01937635001316,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,00225,6105,3.0000,162.00,AGUA DE COCO 1 LITRO CX C6 SUDESTE,CX,7898681940059,20098921,1701100,19.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00,entrada,24201204983035000300550010001458641518005122,2020-12-29T00:00:00-03:00,04983035000300,01937635001316,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,00341,6105,2.0000,84.00,AGUA DE COCO 300ML CX12 SUDESTE,CX,7898681940042,20098921,1701100,10.08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00,entrada,24201204983035000300550010001458641518005122,2020-12-29T00:00:00-03:00,04983035000300,01937635001316,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,000000002156173027,6401,3.0000,397.23,CREME DE LEITE TRAD VC 500G CX 12,CX,17898205920229,04022930,1701900,47.67,49.82,541.62,NaN,NaN,NaN,NaN,NaN,10,entrada,31201107757005000617550010002736321057445880,2020-11-30T22:28:34-03:00,07757005000617,01937635001316,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5532703,17,07891035024177,5102,1.0000,21.58,INSET.SBP M.AUT.C.25,UN,NaN,38089119,NaN,3.88,NaN,NaN,NaN,NaN,NaN,21.58,NaN,00,saida,35201201937635001316590006403151868640701710,20201231,01937635001316,NaN,NaN,NaN,NaN,21.58,21.58,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5532704,18,07891156002030,5405,1.0000,8.29,LEIT.FER.YAK.40 480g,UN,NaN,04039000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.29,NaN,60,saida,35201201937635001316590006403151868640701710,20201231,01937635001316,NaN,NaN,NaN,NaN,8.29,8.29,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5532705,19,07891156002030,5405,1.0000,8.29,LEIT.FER.YAK.40 480g,UN,NaN,04039000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.29,NaN,60,saida,35201201937635001316590006403151868640701710,20201231,01937635001316,NaN,NaN,NaN,NaN,8.29,8.29,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5532706,20,00000078930780,5405,1.0000,10.69,DES.DOV.R.ON M.C.D50,UN,NaN,33072010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.69,NaN,60,saida,35201201937635001316590006403151868640701710,20201231,01937635001316,NaN,NaN,NaN,NaN,10.69,10.69,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5532707,21,07891097001345,5405,1.0000,10.95,MANT.PRES.S SAL 200g,UN,NaN,04051000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.95,NaN,60,saida,35201201937635001316590006403151868640701710,20201231,01937635001316,NaN,NaN,NaN,NaN,10.95,10.95,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
tabela_1[tabela_1['Chave Acesso NFe'] == '35201201937635001316590006738400000018610274']

,Número Item,Código Produto ou Serviço,CFOP,Quantidade Comercial,Valor Produto ou Serviço,Descrição Produto,Unidade Comercial,Código GTIN,Código NCM,CEST,Valor ICMS Operação,Valor ICMS Substituição Tributária,Valor Base Cálculo ICMS Substituição Tributária,Valor Base de Cálculo ICMS ST Retido,Valor ICMS Substituto,Valor ICMS ST Retido,Valor Total NFE do Produto,Valor Desconto Incondicional,CST ICMS,Tipo,Chave Acesso NFe,Data Emissão,Número CNPJ Emitente,Número CNPJ Destinatário,Valor Total IPI,Código CEST,Valor Base Cálculo ICMS ST Retido Operação Anterior,Valor Unitário Comercial,Valor Unitário Tributação,Quantidade Tributável,Valor Outras Despesas Acessórias,Valor Dedução,Valor Desconto Condicional,Descrição Produto (original),Valor Icms Efet,Código CEST (char),Valor Total Tributo,Valor ICMS ST Retido Operação Anterior
74982,1,00000078600010,5102,1.0000,1.99,BALA TIC TAC MENTA 1,UN,NaN,17049020,NaN,0.36,NaN,NaN,NaN,NaN,NaN,1.99,NaN,00,saida,35201201937635001316590006738400000018610274,20201222,01937635001316,NaN,NaN,NaN,NaN,1.99,1.99,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74983,2,00000000000659,5102,0.0200,0.16,BATATA kg,KG,NaN,07019000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.16,NaN,40,saida,35201201937635001316590006738400000018610274,20201222,01937635001316,NaN,NaN,NaN,NaN,7.99,7.99,0.0200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2803845,1,00000078600010,5102,1.0000,1.99,BALA TIC TAC MENTA 1,UN,NaN,17049020,NaN,0.36,NaN,NaN,NaN,NaN,NaN,1.99,NaN,00,saida,35201201937635001316590006738400000018610274,20201222,01937635001316,NaN,NaN,NaN,NaN,1.99,1.99,1.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2803846,2,00000000000659,5102,0.0200,0.16,BATATA kg,KG,NaN,07019000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.16,NaN,40,saida,35201201937635001316590006738400000018610274,20201222,01937635001316,NaN,NaN,NaN,NaN,7.99,7.99,0.0200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
# tabela_1['Código Produto ou Serviço'] = tabela_1['Código Produto ou Serviço'].astype(str)
# tabela_1['Data Emissão'] = pd.to_datetime(tabela_1['Data Emissão'].str.slice(0,10),format='mixed')

uso_complementar = input('Haverá uso de nota complementar ? ')

# Leitura do arquivo da complementar
if uso_complementar.lower() == 'sim':
 
    complementar = ler_arquivo_para_dataframe(bucket_name, f"Cat42/{nome_empresa.title()}/Complementar/complementar.xlsx", file_type='xlsx')
    complementar['Produto'] = complementar['Produto'].astype(str)
    complementar['Item NFE Origem'] = complementar['Item NFE Origem'].astype(int)

if uso_complementar.lower() == 'não':
    colunas = ['Chave Acesso NFe', 'Item NFE Origem', 'EAN', 'Produto',
                       'Quantidade Comercial', 'Valor Produto ou Serviço', 'Valor Base Cálculo ICMS ST Retido Operação Anterior',
                       'vPMC', 'anvisa', 'vBCST', 'ICMS ST Retido-Base de Cálculo','ALIQUOTA', 'ICMS ST Retido- Valor']
    
    complementar = pd.DataFrame(columns=colunas)
    for coluna in colunas:
        complementar[coluna] = np.zeros(shape=tabela_1.shape[0])

# Leitura da tabela da efd_mod55 para um data frame

query = f"SELECT * FROM modelo55 WHERE cnpj = '{cnpj}';"

efd = pd.read_sql_query(query, engine)
if efd.shape[0] == 0:
    print(f'Tabela modelo 55 da loja {nome_empresa.title()}:{cnpj} não consta no banco. Favor verificar')
    sys.exit()

# Alteração do tipo de dado

efd['codigo_do_item'] = efd['codigo_do_item'].astype(float)

# Leitura da tabela da efd_mod59 para um data frame

query = f"SELECT * FROM modelo59 WHERE modelo59.cnpj = '{cnpj}';"

efd_mod59 = pd.read_sql_query(query, engine)
if (efd_mod59.shape[0] == 0) and (nome_empresa != 'ladakh'):
    print(f'Tabela modelo 59 da loja {nome_empresa.title()}:{cnpj} não consta no banco. Favor verificar')
    sys.exit()


# Formatação da coluna de data
efd_mod59['data_efds'] = pd.to_datetime(efd_mod59['data_efds'], format='%m/%Y')

# Alteração do tipo de dado

# efd_mod59['codigo_produto'] = efd_mod59['codigo_produto'].astype(str)

# Retirada dos valores negativos de base de calculo da complementar

complementar['ICMS ST Retido-Base de Cálculo'] = complementar['ICMS ST Retido-Base de Cálculo'].astype(float)
complementar['ICMS ST Retido- Valor'] = complementar['ICMS ST Retido- Valor'].astype(float)
complementar_final = complementar[complementar['ICMS ST Retido-Base de Cálculo'] >= 0]

# Formatação da coluna de data da tabela 1

tabela_1['Data Emissão'] = pd.to_datetime(tabela_1['Data Emissão'],format='mixed')

# Formatação da coluna Valor Produto ou Serviço para o tipo correto

tabela_1['Valor Produto ou Serviço'] = tabela_1['Valor Produto ou Serviço'].astype(float)

# Preenchimento da coluna bc_complementar_total_complementar

tabela_1['Número Item'] = tabela_1['Número Item'].astype(float)
tabela_1['Chave Acesso NFe'] = tabela_1['Chave Acesso NFe'].astype(str)

complementar_final['Item NFE Origem'] = complementar_final['Item NFE Origem'].astype(float)
complementar_final['Chave Acesso NFe'] = complementar_final['Chave Acesso NFe'].astype(str)
bc_df = complementar_final[['Chave Acesso NFe', 'Item NFE Origem', 'vBCST', 'ICMS ST Retido-Base de Cálculo', 'Produto', 'vPMC']]
merged_df = pd.merge(tabela_1, bc_df, left_on=['Chave Acesso NFe', 'Número Item'],
                    right_on=['Chave Acesso NFe', 'Item NFE Origem'], how='left')

# merged_df = merged_df.drop('Unnamed: 0', axis=1)
merged_df = merged_df.drop_duplicates()

# Preenchimento da coluna bc_complementar_total_item_original

merged_df['Valor Base de Cálculo ICMS ST Retido'] = merged_df['Valor Base de Cálculo ICMS ST Retido'].astype(float).fillna(0)
merged_df['Valor ICMS Operação'] = merged_df['Valor ICMS Operação'].astype(float).fillna(0)

merged_df['bc_complementar_total_item_original'] = merged_df['ICMS ST Retido-Base de Cálculo']

# Formatação da coluna de data
efd['data_saida'] = efd['data_saida'].replace('', np.nan)
efd['data_saida'] = pd.to_datetime(efd['data_saida'], format='%d/%m/%Y')

# Mudança do tipo de dado para string

efd['codigo_do_item'] = efd['codigo_do_item'].astype(float)
merged_df['Número Item'] = merged_df['Número Item'].astype(float)

# Mudança do tipo de dado para string

efd['chave_nfe'] = efd['chave_nfe'].astype(str)
merged_df['Chave Acesso NFe'] = merged_df['Chave Acesso NFe'].astype(str)

#Preenchimento das colunas referentes a informações da efd
merged = pd.merge(merged_df, efd[['chave_nfe','data_saida', 'codigo_do_item',
                                  'cfop', 'codigo_produto', 'quantidade',
                                 'descricao_produto', 'ean', 'ncm', 'cest', 'indice_operacao']],
                 left_on=['Chave Acesso NFe', 'Número Item'],
                 right_on=['chave_nfe', 'codigo_do_item'],
                 how='left')

merged = merged.drop_duplicates()

# Definição de coluna com para chave-item para identificação de erros

merged['CHAVE_ITEM'] = merged['Chave Acesso NFe'].astype(str) + '-' + merged['Número Item'].astype(str)
merged = merged.drop_duplicates(subset='CHAVE_ITEM', keep='first')

# Identificação de algum possível erro em relação à unicidade de pares chave-item

merged['CHAVE_ITEM'] = merged['Chave Acesso NFe'].astype(str) + '-' + merged['Número Item'].astype(str)

duplicate_mask = merged['CHAVE_ITEM'].duplicated(keep=False)
duplicate_df = merged[duplicate_mask]
if duplicate_df.shape[0] > 0:
    print('Erro encontrado: combinação Chave-Item duplicada. Por favor verificar')
    sys.exit()

# Leitura para um dataframe da tabela de produtos
# do banco de dados

query = f"SELECT * FROM produtos where empresa = '{cnpj_produtos}'"
produtos = pd.read_sql_query(query, engine)

# Checagem de erro em relação à duplicidade de aliquota na tabela de produtos

mask = produtos.groupby('codigo_produto')['icms'].transform('nunique') > 1

# Filtrar as linhas que atendem à condição
result = produtos[mask]
result = result.sort_values(by='codigo_produto')
if result.shape[0] > 0:
    print('DUPLICAÇÃO DE ALIQUOTA NA TABELA DE PRODUTOS, FAVOR CHECAR')
    sys.exit()

# Ajustes de dados e definição de informações para aplicação da regras de 
# filtragem dos dados presentes na efd

efd['codigo_produto'] = efd['codigo_produto'].astype(str)
efd['CHAVE_ITEM'] = efd['chave_nfe'] + '-' + efd['codigo_do_item'].astype(str)
cods = efd['codigo_produto'].unique()
merged['Produto'] = merged['Produto'].astype(str)
merged['Chave-Item'] = merged['Chave Acesso NFe'] + '-' + merged['Número Item'].astype(str)

chave_mod_59 = efd_mod59['chv_cfe'].unique()
chave_mod_55 = efd['chave_nfe'].unique()

# Aplicação das regras

# Regra 1
df_1 = merged[merged['Chave-Item'].isin(efd['CHAVE_ITEM'])]
df_1['Tipo'] = 'entrada'

# Regra 2
efd_filtrado  = efd[(efd['codigo_do_item'].isna()) & (efd['indice_operacao'] == '1')]
df_2 = merged[merged['Chave Acesso NFe'].isin(efd_filtrado['chave_nfe'])]
df_2['Tipo'] = 'saida'
# Regra 3
df_3 =  merged[merged['Chave Acesso NFe'].isin(chave_mod_59)]
df_3['Tipo'] = 'saida'

merged_novo = pd.concat([df_1,  df_2, df_3])

merged_novo['IND_OPER'] = np.where((merged_novo['Tipo'] == 'saida'),
                            1, 0)

merged_novo = merged_novo.drop_duplicates()
merged_novo['Produto'] = np.where((merged_novo['Tipo'] == 'entrada') & (~merged_novo['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (merged_novo['CFOP'].astype(float) != 5409),
                               merged_novo['codigo_produto'], merged_novo['Código Produto ou Serviço'])
merged_novo['Produto'] = merged_novo['Produto'].astype(str)

df_merged = pd.merge(merged_novo, produtos[['codigo_produto', 'icms', 'cest', 'mva_antes']],
                    left_on=['Produto'], right_on=['codigo_produto'],
                    how='left')


# Checagem de duplicação de chave-item

df_merged['CHAVE_ITEM'] = df_merged['Chave Acesso NFe'].astype(str) + '-' + df_merged['Número Item'].astype(str)

duplicate_mask = df_merged['CHAVE_ITEM'].duplicated(keep=False)
duplicate_df = df_merged[duplicate_mask]
if duplicate_df.shape[0] > 0:
    print('Erro encontrado: combinação Chave-Item duplicada. Por favor verificar')
    sys.exit()

df_merged = df_merged.drop_duplicates()

df = df_merged.copy()

# Retirada de linhas duplicadas

df = df.drop_duplicates()

# Preenchimento da coluna ICMS_TOT
df['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = df['Valor Base Cálculo ICMS ST Retido Operação Anterior'].fillna(0)
df['Valor ICMS Substituição Tributária'] = df['Valor ICMS Substituição Tributária'].astype(float).fillna(0)
df['Valor ICMS Operação'] = df['Valor ICMS Operação'].astype(float).fillna(0)
df['Valor ICMS ST Retido'] = df['Valor ICMS ST Retido'].astype(float).fillna(0)
df['Valor ICMS Substituto'] = df['Valor ICMS Substituto'].astype(float).fillna(0)
df['icms'] = df['icms'].astype(str).replace('None', np.nan)

df['icms'] = df['icms'].str.replace('-', '0').fillna('0').str.replace('nan', '0')
df['vBCST'] = df['vBCST'].astype(float).fillna(0)

# Geração da coluna CHV_DOC
tabela_2 = pd.DataFrame()

tabela_2['CHV_DOC'] = df['Chave Acesso NFe']

# Geração da coluna DATA

tabela_2['DATA'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)),
                            df['data_saida'], df['Data Emissão'])

# Geração da coluna NUM_ITEM

tabela_2['NUM_ITEM'] = df['Número Item']

# Preenchimento da coluna CFOP

tabela_2['CFOP'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)),
                               df['cfop'], df['CFOP'])

tabela_2['CFOP'] = tabela_2['CFOP'].astype(str).str.replace(r'\.0$', '', regex=True)

# Preenchimento da coluna COD_ITEM

tabela_2['COD_ITEM'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (~df['CFOP'].astype(float).isin([5202, 6202, 5409, 5411])),
                               df['Produto'], 
                               df['Código Produto ou Serviço'])

tabela_2['COD_ITEM'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5405, 5152])) & (df['cfop'].astype(float) == 1409),
                                df['Código Produto ou Serviço'],
                                tabela_2['COD_ITEM'])

tabela_2['COD_ITEM'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5411, 5202])),
                                df['Produto'],
                                tabela_2['COD_ITEM'])

tabela_2['MVA'] = df_merged['mva_antes'].astype(str).replace('-', np.nan).replace('None', np.nan).astype(float)


# Preenchimento das colunas QTD_NOTA, QTD_CAT e QTD_EFD

tabela_2['QTD_NOTA'] = df['Quantidade Comercial'].astype(float)
tabela_2['QTD_CAT'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (~df['CFOP'].astype(float).isin([5202, 6202, 5409, 5411])),
                                df['quantidade'], df['Quantidade Comercial'])
tabela_2['QTD_CAT'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5405, 5152])) & (df['cfop'].astype(float) == 1409),
                                df['Quantidade Comercial'],
                                tabela_2['QTD_CAT'])

tabela_2['QTD_CAT'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5411, 5202])),
                                df['quantidade'],
                                tabela_2['QTD_CAT'])

tabela_2

Haverá uso de nota complementar ?  não

C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\1899133137.py:159: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['Tipo'] = 'entrada'
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\1899133137.py:167: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_3['Tipo'] = 'saida'
C:\Users\vinic\AppData\Local\Temp\ipykernel_14680\1899133137.py:203: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = df['Valor Base Cálculo ICMS ST Retido Operação Anterior'].fillna(0)

,CHV_DOC,DATA,NUM_ITEM,CFOP,COD_ITEM,MVA,QTD_NOTA,QTD_CAT
0,24201204983035000300550010001458641518005122,2020-12-30,1.0,2403,1000036545,NaN,3.0,2
1,24201204983035000300550010001458641518005122,2020-12-30,2.0,2403,1000036546,NaN,2.0,3
2,31201107757005000617550010002736321057445880,2020-12-08,1.0,2403,1000023693,NaN,3.0,3
3,31201107757005000617550010002736321057445880,2020-12-08,2.0,2403,1000023694,NaN,1.0,1
4,31201107757005000617550010002736321057445880,2020-12-08,3.0,2403,1000025848,NaN,3.0,3
...,...,...,...,...,...,...,...,...
2754413,35201201937635001316590006403151868640701710,2020-12-31,17.0,5102,07891035024177,NaN,1.0,1.0000
2754414,35201201937635001316590006403151868640701710,2020-12-31,18.0,5405,07891156002030,NaN,1.0,1.0000
2754415,35201201937635001316590006403151868640701710,2020-12-31,19.0,5405,07891156002030,NaN,1.0,1.0000
2754416,35201201937635001316590006403151868640701710,2020-12-31,20.0,5405,00000078930780,NaN,1.0,1.0000
2754417,35201201937635001316590006403151868640701710,2020-12-31,21.0,5405,07891097001345,NaN,1.0,1.0000

In [42]:
tabela_2['QTD_NOTA'] = tabela_2['QTD_NOTA'].astype(str).str.replace(r'\.0$', '', regex=True)
tabela_2['QTD_CAT'] = tabela_2['QTD_CAT'].astype(str).str.replace(r'\.0$', '', regex=True)
tabela_2['QTD_EFD'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)),
                                df['quantidade'], np.nan)


# Preenchimento da coluna DESCRICAO

tabela_2['DESCRICAO'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (~df['CFOP'].astype(float).isin([5202, 6202, 5409, 5411])),
                               df['descricao_produto'], df['Descrição Produto'])

tabela_2['DESCRICAO'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5405, 5152])) & (df['cfop'].astype(float) == 1409),
                                df['Descrição Produto'],
                                tabela_2['DESCRICAO'])

tabela_2['DESCRICAO'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)) & (df['CFOP'].astype(float).isin([5411, 5202])),
                                df['descricao_produto'],
                                tabela_2['DESCRICAO'])

# Preenchimento da coluna CODIGO_BARRA


tabela_2['CODIGO_BARRA'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)),
                               df['ean'], df['Código GTIN'])

# Preenchimento da coluna UNIDADE

tabela_2['UNIDADE'] = df['Unidade Comercial']

# Preenchimento da coluna N C M

df['N C M'] = np.where((df['Tipo'] == 'entrada') & (~df['Chave Acesso NFe'].str.slice(6,20).isin(cnpjs)),
                               df['ncm'], df['Código NCM'])

tabela_2['N C M'] = np.where(df['N C M'].notnull(),
                               df['N C M'], df['Código NCM'])

# Preenchimento da coluna ALIQUOTA

tabela_2['ALIQUOTA'] = df['icms']
tabela_2['ALIQUOTA'] = tabela_2['ALIQUOTA'].astype(str).str.replace(r'\.0$','', regex=True).astype(str).replace('-', np.nan).astype(float)

# Preenchimento da coluna CEST

tabela_2['CEST'] = df['cest_y']                        

# Preenchimento da coluna Entr_PCAT

cfops = [1102, 1202, 1403, 1409, 1411, 
         1949, 2101, 2102, 2202, 2209, 
         2401, 2403, 2405, 2409, 
         2411, 2414, 2949, 5101, 5102, 
         5117, 5118, 
         5120, 5152, 5201, 5202, 
         5210, 5401, 5403, 5405, 
         5409, 5410, 5411, 5413, 5551,
         5556, 5910, 5911, 5922, 5923, 
         5927, 
         5929, 5949, 6101, 6102, 6103, 
         6108, 6117, 6119, 6152, 6202, 
         6401, 6403, 6404, 6409, 
         6411, 6414, 6556, 6910, 
         6911, 6922, 6923]

tabela_2['Entr_PCAT'] = np.where((tabela_2['CFOP'].astype(int).isin(cfops)) & (tabela_2['CEST'].notnull()),
                                 1,
                                 0)


# Preenchimento das colunas CNPJ EMITENTE e CNPJ DESTINATARIO

tabela_2['CNPJ EMITENTE'] = df['Número CNPJ Emitente']
tabela_2['CNPJ DESTINATARIO'] = df['Número CNPJ Destinatário']

# Preenchimento da coluna IND_OPER

tabela_2['IND_OPER'] = df['IND_OPER']

# # Preenchimento da coluna VALOR
# tabela_2['VALOR'] = df['Valor Produto ou Serviço'].astype(str).replace('-', np.nan).astype(float)

# # Definição de mais colunas

# tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = df['Valor Base Cálculo ICMS ST Retido Operação Anterior']
# tabela_2['Valor Base Cálculo ICMS Substituição Tributária'] = df['Valor Base Cálculo ICMS Substituição Tributária']
# tabela_2['Valor Complementar'] = df['bc_complementar_total_item_original']
# tabela_2['vBCST'] = df['vBCST']
# tabela_2['Valor ICMS Operação'] = df['Valor ICMS Operação']
# tabela_2['Valor ICMS Substituição Tributária'] = df['Valor ICMS Substituição Tributária']
# tabela_2['Valor ICMS ST Retido'] = df['Valor ICMS ST Retido']
# tabela_2['Valor ICMS Substituto'] = df['Valor ICMS Substituto']
# tabela_2['QTD_CAT'] = tabela_2['QTD_CAT'].replace('nan', np.nan)
# tabela_2['CST'] = df['CST ICMS']
# tabela_2['FONTE'] = df['Tipo']

# # Preenchimento da coluna ICMS_TOT 
# tabela_2['Valor ICMS Operação'] = np.where((tabela_2['FONTE'] == 'entrada') & (~tabela_2['CHV_DOC'].str.slice(6,20).isin(cnpjs)),
#                                      np.where(tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] <= tabela_2['vBCST'],
#                                               tabela_2['Valor ICMS Operação'],
#                                               tabela_2['Valor ICMS Substituto']),
#                                               tabela_2['Valor ICMS Operação'])

# tabela_2['Valor ICMS Operação'] = tabela_2['Valor ICMS Operação'].fillna(0)
# tabela_2['Valor ICMS Substituição Tributária'] = tabela_2['Valor ICMS Substituição Tributária'].fillna(0)
# tabela_2['Valor ICMS ST Retido'] = tabela_2['Valor ICMS ST Retido'].fillna(0)
# tabela_2['Valor ICMS Substituto'] = tabela_2['Valor ICMS Substituto'].fillna(0)
# tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] = tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'].fillna(0)
# tabela_2['Valor Complementar'] = tabela_2['Valor Complementar'].fillna(0)
# tabela_2['vBCST'] = tabela_2['vBCST'].fillna(0)
# tabela_2['ALIQUOTA'] = tabela_2['ALIQUOTA'].fillna(0)

# condicao_entrada = (tabela_2['FONTE'] == 'entrada') & (~tabela_2['CHV_DOC'].str.slice(6, 20).isin(cnpjs))

# condicao_base_icms = tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] <= tabela_2['vBCST']
# condicao_zero_valores = (
#     (tabela_2['Valor Complementar'] == 0) &
#     (tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] == 0) &
#     (tabela_2['Valor ICMS Operação'] == 0) &
#     (tabela_2['Valor ICMS Substituição Tributária'] == 0)
# )

# # Ajustando a lógica para garantir que a soma dos valores ICMS retido e substituto aconteça quando os outros valores forem 0
# tabela_2['ICMS_TOT'] = np.where(
#     condicao_entrada,
#     np.where(
#         condicao_base_icms,
#         np.where(
#             condicao_zero_valores,
#             tabela_2['Valor ICMS ST Retido'] + tabela_2['Valor ICMS Substituto'],  # Garantir que essa soma seja feita
#             np.maximum(
#                 tabela_2['Valor ICMS Operação'] + tabela_2['Valor ICMS Substituição Tributária'],
#                 (tabela_2['Valor Base Cálculo ICMS ST Retido Operação Anterior'] + tabela_2['Valor Complementar']) * tabela_2['ALIQUOTA'].astype(float) / 100
#             )
#         ),
#         np.where(
#             tabela_2['vBCST'] != 0,
#             np.maximum(
#                 tabela_2['Valor ICMS Operação'] + tabela_2['Valor ICMS Substituição Tributária'],
#                 (tabela_2['vBCST'] + tabela_2['Valor Complementar']) * tabela_2['ALIQUOTA'].astype(float) / 100
#             ),
#             tabela_2['Valor ICMS ST Retido'] + tabela_2['Valor ICMS Substituto']  # Garantir que a soma de ICMS ST Retido e Substituto aconteça aqui também
#         )
#     ),
#     np.nan  # Valor a ser atribuído quando a condição principal não for atendida
# )

# cond_1 = tabela_2['CFOP'].isin([1102, 2102])
# cond_2 = (tabela_2['CST'] != 60) & (tabela_2['CFOP'].isin([1202, 2202]))

# tabela_2['ICMS_TOT'] = np.where(cond_1 | cond_2, 
#                                 np.nan, 
#                                 tabela_2['ICMS_TOT'])

# tabela_2['Valor ICMS Operação'] = np.where(tabela_2['Valor ICMS Operação'] == 0,
#                                            tabela_2['Valor ICMS Substituto'],
#                                            tabela_2['Valor ICMS Operação'])

# tabela_2['ICMS_TOT_SAIDA'] = np.where((tabela_2['IND_OPER'] == 1),
#                                          (tabela_2['VALOR'].astype(float) * (tabela_2['ALIQUOTA'].astype(float) / 100)) * (tabela_2['MVA'].astype(float) + 1),
#                                          np.nan)

# # tabela_2 = tabela_2[tabela_2['Entr_PCAT'] == 1]

# query = 'select * from cfop'
# df_2 = pd.read_sql_query(query, connection)

# tabela_2['CFOP'] = tabela_2['CFOP'].astype(int)
# df_2['cfop'] = df_2['cfop'].astype(int)

# tabela_2 = tabela_2.merge(df_2, left_on='CFOP', right_on='cfop')
# tabela_2['DATA'] = pd.to_datetime(tabela_2['DATA'], format='%Y-%m-%d')
# # df_new = df_new.sort_values(by=['COD_ITEM', 'DATA', 'IND_OPER'])
# tabela_2['ALIQUOTA'] = tabela_2['ALIQUOTA'].astype(str).replace('nan', np.nan)

# # Preenchimento da coluna VL_CONFR
# tabela_2['CFOP'] = tabela_2['CFOP'].astype(int)
# tabela_2['IND_OPER'] = tabela_2['IND_OPER'].astype(int)
# tabela_2['sinal'] = tabela_2['sinal'].astype(int)

# mask = (tabela_2['IND_OPER'] == 1) & (tabela_2['sinal'] == 1) & \
#        (~tabela_2['CFOP'].isin([5409, 5927])) 
# # Calculate the values using NumPy operations
# values = np.where(mask, tabela_2['VALOR'] * (tabela_2['ALIQUOTA'].fillna(0).astype(float) / 100), np.nan)

# # Assign the calculated values to the 'vl_confr' column
        
# tabela_2['VL_CONFR'] = values

# tabela_2['SUB_TIPO'] = tabela_2['sinal']
# tabela_2['VL_CONFR_0'] = tabela_2['VL_CONFR']

# tabela_2['ALIQUOTA'] = tabela_2['ALIQUOTA'].astype(str).replace('nan', np.nan)

# # Preenchimento da coluna COD_LEGAL
# tabela_2['CFOP'] = tabela_2['CFOP'].astype(int)
# tabela_2['IND_OPER'] = tabela_2['IND_OPER'].astype(int)
# tabela_2['SUB_TIPO'] = tabela_2['SUB_TIPO'].astype(int)

# conditions = [
#     (tabela_2['CST'] == 40) & (tabela_2['IND_OPER'] == 1),
#     tabela_2['CFOP'].isin([6102, 6152, 6404, 6409, 6108, 6117]),
#     tabela_2['CFOP'].isin([5102, 5152, 5201, 5202, 5210, 5409,
#                            5410, 5411, 5413, 5556, 5910, 5922,
#                            5949, 6202, 6411, 6922, 6403, 6910]),
#     (tabela_2['CFOP'] == 5927),
#     (tabela_2['CFOP'] == 5405),
#     (tabela_2['CFOP'].isin([5117, 5120, 5929])) & (tabela_2['CST'] == 60),
#     tabela_2['ALIQUOTA'].isnull(),
#     (tabela_2['CFOP'].isin([1102, 1411, 2102, 2202, 1403, 2411, 1202, 2403, 1949]))
# ]



# choices = [3, 4, 0, 2, 1, 1, 0, np.nan]

# # If none of the conditions are met, the default choice is 1
# default_choice = 0

# # Use numpy.select to set values for 'COD_LEGAL'
# tabela_2['COD_LEGAL'] = np.select(conditions, choices, default=default_choice)

# # Substituição dos valores nulos de aliquota por 0

# tabela_2['ALIQUOTA'] = tabela_2['ALIQUOTA'].astype(str).replace('nan', np.nan).fillna(0).astype(float)

# # Criação de coluna para checagem de erro em fator de conversão

# tabela_2 = tabela_2[(tabela_2['QTD_NOTA'] != 'nan') & (tabela_2['QTD_NOTA'].astype(float) > 0)]
# tabela_2['QTD_NOTA'] = tabela_2['QTD_NOTA'].astype(float)
# tabela_2['QTD_CAT'] = tabela_2['QTD_CAT'].astype(float)
# # tabela_2['CHECAGEM'] = (tabela_2['QTD_CAT']/tabela_2['QTD_NOTA']).round(3)

# # # Geração de tabela para checagem de erro em fator de conversão

# # pivot_table = tabela_2[(tabela_2['IND_OPER'] == 0) & (~tabela_2['CHV_DOC'].str.slice(6,20).isin(cnpjs)) & (~tabela_2['CFOP'].astype(float).isin([1202, 2202, 1411,2411]))].pivot_table(index=['COD_ITEM', 'UNIDADE'], values='CHECAGEM', aggfunc='nunique').reset_index()

# # # Checagem de erro em fator de conversão

# # cod_items_with_multiple_values = pivot_table[pivot_table['CHECAGEM'] > 1]['COD_ITEM']
# # if cod_items_with_multiple_values.shape[0] > 0:
# #     print('Erro encontrado: Fator de conversão errado, favor verificar')
# #     cods = pivot_table[pivot_table['CHECAGEM'] > 1]['COD_ITEM'].values
# #     salvar_dataframe_no_s3(tabela_2[(tabela_2['COD_ITEM'].isin(cods)) & (tabela_2['IND_OPER'] == 0)], bucket_name=bucket_name,
# #                            s3_key=f'Cat42/{nome_empresa.title()}/cods_a_verificar_{nome_empresa}_{cnpj}.xlsx', file_type='xlsx')
# #     sys.exit()

# # tabela_2 = tabela_2[(tabela_2['DATA'] >= '2023-01-01') & (tabela_2['DATA'] <= '2023-12-31')]
# # data = tabela_2['DATA'].astype(str).iloc[0][:4]
# tabela_2 = tabela_2[(tabela_2['DATA'] >= '2020-01-01')]
# tabela_2_filt = tabela_2[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'MVA',
#                     'IND_OPER', 'SUB_TIPO', 'QTD_CAT', 'QTD_EFD', 'ICMS_TOT', 'ICMS_TOT_SAIDA', 'VL_CONFR_0', 'COD_LEGAL',
#                     'ALIQUOTA', 'VALOR', 'Valor Base Cálculo ICMS ST Retido Operação Anterior',
#                     'Valor Complementar', 'Valor ICMS Substituição Tributária', 'Valor ICMS Operação',
#                     'Valor ICMS ST Retido', 'Valor ICMS Substituto', 'CST',
#                     'DESCRICAO', 'CODIGO_BARRA', 'UNIDADE', 'N C M','CEST', 'CNPJ EMITENTE', 'CNPJ DESTINATARIO',
#                     'Valor Base Cálculo ICMS Substituição Tributária', 'vBCST', 'FONTE']]
# tabela_2_filt
tabela_2

,CHV_DOC,DATA,NUM_ITEM,CFOP,COD_ITEM,MVA,QTD_NOTA,QTD_CAT,QTD_EFD,DESCRICAO,CODIGO_BARRA,UNIDADE,N C M,ALIQUOTA,CEST,Entr_PCAT,CNPJ EMITENTE,CNPJ DESTINATARIO,IND_OPER
0,24201204983035000300550010001458641518005122,2020-12-30,1.0,2403,1000036545,NaN,3,2,2,AGUA COCO AQUA COCO 300ML,None,CX,20098921,0.0,NaN,0,04983035000300,01937635001316,0
1,24201204983035000300550010001458641518005122,2020-12-30,2.0,2403,1000036546,NaN,2,3,3,AGUA COCO AQUA COCO 1L,None,CX,20098921,0.0,NaN,0,04983035000300,01937635001316,0
2,31201107757005000617550010002736321057445880,2020-12-08,1.0,2403,1000023693,NaN,3,3,3,CREME LEIT.VDE.CAMPO FRES.500G,None,CX,04022930,0.0,NaN,0,07757005000617,01937635001316,0
3,31201107757005000617550010002736321057445880,2020-12-08,2.0,2403,1000023694,NaN,1,1,1,CREME LEIT.VDE.CAMPO LACFREE 500G,None,CX,04022930,0.0,NaN,0,07757005000617,01937635001316,0
4,31201107757005000617550010002736321057445880,2020-12-08,3.0,2403,1000025848,NaN,3,3,3,IOGURTE VDE.CAMPO NAT.WHEY DC.LEIT.250G,None,CX,04031000,0.0,NaN,0,07757005000617,01937635001316,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2754413,35201201937635001316590006403151868640701710,2020-12-31,17.0,5102,07891035024177,NaN,1,1.0000,NaN,INSET.SBP M.AUT.C.25,NaN,UN,38089119,0.0,NaN,0,01937635001316,NaN,1
2754414,35201201937635001316590006403151868640701710,2020-12-31,18.0,5405,07891156002030,NaN,1,1.0000,NaN,LEIT.FER.YAK.40 480g,NaN,UN,04039000,0.0,NaN,0,01937635001316,NaN,1
2754415,35201201937635001316590006403151868640701710,2020-12-31,19.0,5405,07891156002030,NaN,1,1.0000,NaN,LEIT.FER.YAK.40 480g,NaN,UN,04039000,0.0,NaN,0,01937635001316,NaN,1
2754416,35201201937635001316590006403151868640701710,2020-12-31,20.0,5405,00000078930780,NaN,1,1.0000,NaN,DES.DOV.R.ON M.C.D50,NaN,UN,33072010,0.0,NaN,0,01937635001316,NaN,1
2754417,35201201937635001316590006403151868640701710,2020-12-31,21.0,5405,07891097001345,NaN,1,1.0000,NaN,MANT.PRES.S SAL 200g,NaN,UN,04051000,0.0,NaN,0,01937635001316,NaN,1

In [56]:
produtos[produtos['codigo_produto'].isin(tabela_2[tabela_2['IND_OPER'] == 0]['COD_ITEM'].unique())]

,empresa,anvisa,ncm,cest,codigo_produto,descricao,icms,mva_antes,mva_depois,data_valida
16,01937635001316,None,18069000,17.004.00,500000670,MP GRANULADO MAVALERIO CH.CROC.1.010KG,18,0.6365,None,None
17,01937635001316,None,19021100,17.049.02,500000732,MP MASSA BARLETTA PIZZA F030 UN,-,-,None,None
18,01937635001316,None,21069090,17.097.00,500000833,MP ANTIMOFO FLEISCH.1KG,18,0.701,None,None
19,01937635001316,None,21039011,17.039.00,500000912,MP MAIONESE VIGOR LE CHEF SC.1KG,18,0.2891,None,None
20,01937635001316,None,19019090,17.046.00,500001084,MP SOBREMESA LACT.DINIZ LEIT.COND.2KG,-,-,None,None
...,...,...,...,...,...,...,...,...,...,...
5664,01937635001316,None,19059090,17.031.00,82698,MINI RISOLE ZIN PAO PRES QJO ORIG KG,18,0.7861,None,None
5665,01937635001316,None,19059090,17.031.00,82700,BOLINHA ZIN PAO MUS ORIG KG,18,0.7861,None,None
5666,01937635001316,None,16024900,17.079.05,83124,COSTELA PAMP SUI COZ RESF ORIG KG,18,0.4697,None,None
5667,01937635001316,None,16010000,17.076.00,83212,SALSICHA CERAT C ALHO ORIG KG,18,0.4893,None,None
5668,01937635001316,None,16010000,17.076.00,83253,PIG BEEF CERAT C AZEIT ORIG KG,18,0.4893,None,None

In [74]:
# tabela_2 = tabela_2[(tabela_2['DATA'] >= '2020-01-01')]
tabela_2_filt = tabela_2[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'MVA',
                    'IND_OPER', 'SUB_TIPO', 'QTD_CAT', 'QTD_EFD', 'ICMS_TOT', 'ICMS_TOT_SAIDA', 'VL_CONFR_0', 'COD_LEGAL',
                    'ALIQUOTA', 'VALOR', 'Valor Base Cálculo ICMS ST Retido Operação Anterior',
                    'Valor Complementar', 'Valor ICMS Substituição Tributária', 'Valor ICMS Operação',
                    'Valor ICMS ST Retido', 'Valor ICMS Substituto', 'CST',
                    'DESCRICAO', 'CODIGO_BARRA', 'UNIDADE', 'N C M','CEST', 'CNPJ EMITENTE', 'CNPJ DESTINATARIO',
                    'Valor Base Cálculo ICMS Substituição Tributária', 'vBCST', 'FONTE']]

if tabela_2[tabela_2['ALIQUOTA'].isnull()].shape[0] > 0:
    print('Erro encontrado. Existem Alíquotas vazias, favor verificar')
    print('Os seguintes códigos não possuem Aliquota:')
    print(list(tabela_2[tabela_2['ALIQUOTA'].isnull()]['COD_ITEM'].unique()))
    print(tabela_2[tabela_2[['CHV_DOC','COD_ITEM', 'DESCRICAO', 'FONTE']]])
    sys.exit()

tabela_2_filt['COMBINACAO_CHV_NUM'] = tabela_2_filt['CHV_DOC'] + '-' + tabela_2_filt['NUM_ITEM'].astype(str)
# Criando uma coluna temporária para a combinação de CHAVE_ORIGINAL e COD_DO_ITEM em efd
efd['COMBINACAO_CHAVE_COD'] = efd['chave_nfe'] + '-' + efd['codigo_do_item'].astype(str)

# Cenário
condicao_cenario = (
    (tabela_2_filt['IND_OPER'] == 0) &
    (~tabela_2_filt['COMBINACAO_CHV_NUM'].isin(efd['COMBINACAO_CHAVE_COD']))
)

# Verificando se há alguma linha que atende ao cenário
tabela_2_final = tabela_2_filt[~condicao_cenario]
# Checagem de duplicação de par chave-item


tabela_2_final['CHAVE_ITEM'] = tabela_2_final['CHV_DOC'].astype(str) + '-' + tabela_2_final['NUM_ITEM'].astype(str)

duplicate_mask = tabela_2_final['CHAVE_ITEM'].duplicated(keep=False)
duplicate_df = tabela_2_final[duplicate_mask]
if duplicate_df.shape[0] > 0:
    print('Erro encontrado: combinação Chave-Item duplicada. Por favor verificar')
    sys.exit()

tabela_2_final['CHAVE_ITEM'] = tabela_2_final['CHV_DOC'].astype(str) + '-' + tabela_2_final['NUM_ITEM'].astype(str)

duplicate_mask = tabela_2_final['CHAVE_ITEM'].duplicated(keep=False)
duplicate_df = tabela_2_final[duplicate_mask]
if duplicate_df.shape[0] > 0:
    print('Erro encontrado: combinação Chave-Item duplicada. Por favor verificar')
    sys.exit()

tabela_2_final['ICMS_TOT'] = np.where(tabela_2_final['CFOP'].isin([1102, 2102]), np.nan, tabela_2_final['ICMS_TOT'])
tabela_2_final

C:\Users\vinic\AppData\Local\Temp\ipykernel_27576\2331645254.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tabela_2_filt['COMBINACAO_CHV_NUM'] = tabela_2_filt['CHV_DOC'] + '-' + tabela_2_filt['NUM_ITEM'].astype(str)

,CHV_DOC,DATA,CFOP,NUM_ITEM,COD_ITEM,MVA,IND_OPER,SUB_TIPO,QTD_CAT,QTD_EFD,ICMS_TOT,ICMS_TOT_SAIDA,VL_CONFR_0,COD_LEGAL,ALIQUOTA,VALOR,Valor Base Cálculo ICMS ST Retido Operação Anterior,Valor Complementar,Valor ICMS Substituição Tributária,Valor ICMS Operação,Valor ICMS ST Retido,Valor ICMS Substituto,CST,DESCRICAO,CODIGO_BARRA,UNIDADE,N C M,CEST,CNPJ EMITENTE,CNPJ DESTINATARIO,Valor Base Cálculo ICMS Substituição Tributária,vBCST,FONTE,COMBINACAO_CHV_NUM,CHAVE_ITEM
0,24201204983035000300550010001458641518005122,2020-12-30,2403,1.0,1000036545,NaN,0,1,2.0,2,19.44,NaN,NaN,NaN,0.0,162.00,0,0.0,0.00,19.44,0.0,0.0,00,AGUA COCO AQUA COCO 300ML,None,CX,20098921,NaN,04983035000300,01937635001316,NaN,0.0,entrada,24201204983035000300550010001458641518005122-1.0,24201204983035000300550010001458641518005122-1.0
1,24201204983035000300550010001458641518005122,2020-12-30,2403,2.0,1000036546,NaN,0,1,3.0,3,10.08,NaN,NaN,NaN,0.0,84.00,0,0.0,0.00,10.08,0.0,0.0,00,AGUA COCO AQUA COCO 1L,None,CX,20098921,NaN,04983035000300,01937635001316,NaN,0.0,entrada,24201204983035000300550010001458641518005122-2.0,24201204983035000300550010001458641518005122-2.0
2,31201107757005000617550010002736321057445880,2020-12-08,2403,1.0,1000023693,NaN,0,1,3.0,3,97.49,NaN,NaN,NaN,0.0,397.23,0,0.0,49.82,47.67,0.0,0.0,10,CREME LEIT.VDE.CAMPO FRES.500G,None,CX,04022930,NaN,07757005000617,01937635001316,541.62,0.0,entrada,31201107757005000617550010002736321057445880-1.0,31201107757005000617550010002736321057445880-1.0
3,31201107757005000617550010002736321057445880,2020-12-08,2403,2.0,1000023694,NaN,0,1,1.0,1,34.83,NaN,NaN,NaN,0.0,141.88,0,0.0,17.80,17.03,0.0,0.0,10,CREME LEIT.VDE.CAMPO LACFREE 500G,None,CX,04022930,NaN,07757005000617,01937635001316,193.45,0.0,entrada,31201107757005000617550010002736321057445880-2.0,31201107757005000617550010002736321057445880-2.0
4,31201107757005000617550010002736321057445880,2020-12-08,2403,3.0,1000025848,NaN,0,1,3.0,3,56.96,NaN,NaN,NaN,0.0,210.21,0,0.0,31.73,25.23,0.0,0.0,10,IOGURTE VDE.CAMPO NAT.WHEY DC.LEIT.250G,None,CX,04031000,NaN,07757005000617,01937635001316,316.43,0.0,entrada,31201107757005000617550010002736321057445880-3.0,31201107757005000617550010002736321057445880-3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2761715,35201201937635001316590006403151868640701710,2020-12-31,5102,17.0,07891035024177,NaN,1,1,1.0,NaN,NaN,NaN,0.0,0.0,0.0,21.58,0,0.0,0.00,3.88,0.0,0.0,00,INSET.SBP M.AUT.C.25,NaN,UN,38089119,NaN,01937635001316,NaN,NaN,0.0,saida,35201201937635001316590006403151868640701710-17.0,35201201937635001316590006403151868640701710-17.0
2761716,35201201937635001316590006403151868640701710,2020-12-31,5405,18.0,07891156002030,NaN,1,1,1.0,NaN,NaN,NaN,0.0,1.0,0.0,8.29,0,0.0,0.00,0.00,0.0,0.0,60,LEIT.FER.YAK.40 480g,NaN,UN,04039000,NaN,01937635001316,NaN,NaN,0.0,saida,35201201937635001316590006403151868640701710-18.0,35201201937635001316590006403151868640701710-18.0
2761717,35201201937635001316590006403151868640701710,2020-12-31,5405,19.0,07891156002030,NaN,1,1,1.0,NaN,NaN,NaN,0.0,1.0,0.0,8.29,0,0.0,0.00,0.00,0.0,0.0,60,LEIT.FER.YAK.40 480g,NaN,UN,04039000,NaN,01937635001316,NaN,NaN,0.0,saida,35201201937635001316590006403151868640701710-19.0,35201201937635001316590006403151868640701710-19.0
2761718,35201201937635001316590006403151868640701710,2020-12-31,5405,20.0,00000078930780,NaN,1,1,1.0,NaN,NaN,NaN,0.0,1.0,0.0,10.69,0,0.0,0.00,0.00,0.0,0.0,60,DES.DOV.R.ON M.C.D50,NaN,UN,33072010,NaN,01937635001316,NaN,NaN,0.0,saida,35201201937635001316590006403151868640701710-20.0,35201201937635001316590006403151868640701710-20.0
2761719,35201201937635001316590006403151868640701710,2020-12-31,5405,21.0,07891097001345,NaN,1,1,1.0,NaN,NaN,NaN,0.0,1.0,0.0,10.95,0,0.0,0.00,0.00,0.0,0.0,60,MANT.PRES.S SAL 200g,NaN,UN,04051000,NaN,01937635001316,NaN,NaN,0.0,saida,35201201937635001316590006403151868640701710-21.0,35201201937635001316590006403151868640701710-21.0

In [87]:
tabela_2 = ler_arquivo_para_dataframe(bucket_name, f'Cat42/{nome_empresa.title()}/Tabela 2/tabela_2_{nome_empresa.title()}_{cnpj}.xlsx', file_type='xlsx')
tabela_2['COD_ITEM'] = tabela_2['COD_ITEM'].astype(str)

tabela_2

Arquivo 'Cat42/Sonda/Tabela 2/tabela_2_Sonda_01937635001316.xlsx' lido com sucesso!

,CHV_DOC,DATA,CFOP,NUM_ITEM,COD_ITEM,MVA,IND_OPER,SUB_TIPO,QTD_CAT,QTD_EFD,ICMS_TOT,ICMS_TOT_SAIDA,VL_CONFR_0,COD_LEGAL,ALIQUOTA,VALOR,Valor Base Cálculo ICMS ST Retido Operação Anterior,Valor Complementar,Valor ICMS Substituição Tributária,Valor ICMS Operação,Valor ICMS ST Retido,Valor ICMS Substituto,CST,DESCRICAO,CODIGO_BARRA,UNIDADE,N C M,CEST,CNPJ EMITENTE,CNPJ DESTINATARIO,Valor Base Cálculo ICMS Substituição Tributária,vBCST,FONTE,COMBINACAO_CHV_NUM,CHAVE_ITEM
0,31201243816719003042550550002624751726079843,2020-12-18,2403,2,1000034457,0.5245,0,1,30.0,30.0,2400.11,NaN,NaN,NaN,18,8017.52,0,0,2079.41,320.70,0.0,0.0,10.0,BOMBOM FERRERO B READY NUTELLA 22G,NaN,CX,19053200,17.057.00,43816719003042,1937635001316,13333.94,0,entrada,31201243816719003042550550002624751726079843-2.0,31201243816719003042550550002624751726079843-2.0
1,31201243816719003042550550002624751726079843,2020-12-18,2403,7,1000005800,0.6365,0,1,5.0,5.0,521.43,NaN,NaN,NaN,18,1545.36,0,0,459.62,61.81,0.0,0.0,10.0,KINDER OVO C SURPR.MENINO 40G,NaN,CX,18069000,17.004.00,43816719003042,1937635001316,2896.88,0,entrada,31201243816719003042550550002624751726079843-7.0,31201243816719003042550550002624751726079843-7.0
2,31201243816719003042550550002624751726079843,2020-12-18,2403,9,1000005581,0.6365,0,1,35.0,35.0,1336.53,NaN,NaN,NaN,18,5531.56,0,0,672.74,663.79,0.0,0.0,10.0,BOMBOM FERRERO ROCHER 150G,NaN,CX,18069000,17.004.00,43816719003042,1937635001316,7425.12,0,entrada,31201243816719003042550550002624751726079843-9.0,31201243816719003042550550002624751726079843-9.0
3,31201243816719003042550550002624751726079843,2020-12-18,2403,12,1000005576,0.6365,0,1,50.0,50.0,2739.86,NaN,NaN,NaN,18,11339.68,0,0,1379.10,1360.76,0.0,0.0,10.0,BOMBOM FERRERO ROCHER 100G,NaN,CX,18069000,17.004.00,43816719003042,1937635001316,15221.48,0,entrada,31201243816719003042550550002624751726079843-12.0,31201243816719003042550550002624751726079843-12.0
4,31201243816719003042550550002624751726079843,2020-12-18,2403,16,1000004617,0.6365,0,1,127.0,127.0,5364.65,NaN,NaN,NaN,18,17344.57,0,0,3283.30,2081.35,0.0,0.0,10.0,CREME AV.NUTELLA C CAC.350G,NaN,CX,18069000,17.004.00,43816719003042,1937635001316,29803.61,0,entrada,31201243816719003042550550002624751726079843-16.0,31201243816719003042550550002624751726079843-16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2519,43201204330736000189550010004809641406923451,2020-12-16,2403,9,1000006786,0.4753,0,1,2.0,2.0,34.92,NaN,NaN,NaN,18,112.36,0,0,21.44,13.48,0.0,0.0,10.0,AMENDOIM DACOL.TORR.SALG.150G,NaN,CX,20081900,17.106.00,4330736000189,1937635001316,194.01,0,entrada,43201204330736000189550010004809641406923451-9.0,43201204330736000189550010004809641406923451-9.0
2520,43201204330736000189550010004809641406923451,2020-12-16,2102,11,1000005816,NaN,0,1,3.0,3.0,NaN,NaN,NaN,NaN,0,202.32,0,0,0.00,24.28,0.0,0.0,0.0,PE DE MOLEQ.DACOL.Z.AC.100G,NaN,CX,17049090,17.001.02,4330736000189,1937635001316,NaN,0,entrada,43201204330736000189550010004809641406923451-11.0,43201204330736000189550010004809641406923451-11.0
2521,43201204330736000189550010004809641406923451,2020-12-16,2102,12,1000005815,NaN,0,1,2.0,2.0,NaN,NaN,NaN,NaN,0,159.22,0,0,0.00,19.11,0.0,0.0,0.0,PE DE MOLEQ.DACOL.C AC.M 300G,NaN,CX,17049090,17.001.02,4330736000189,1937635001316,NaN,0,entrada,43201204330736000189550010004809641406923451-12.0,43201204330736000189550010004809641406923451-12.0
2522,43201204330736000189550010004809641406923451,2020-12-16,2102,13,1000005644,NaN,0,1,4.0,4.0,NaN,NaN,NaN,NaN,0,428.68,0,0,0.00,51.44,0.0,0.0,0.0,PACOCA DACOL.ROLHA TRAD.210G,NaN,CX,17049090,17.001.02,4330736000189,1937635001316,NaN,0,entrada,43201204330736000189550010004809641406923451-13.0,43201204330736000189550010004809641406923451-13.0
2523,43201204330736000189550010004809641406923451,2020-12-16,2102,15,1000005540,NaN,0,1,5.0,5.0,NaN,NaN,NaN,NaN,0,268.40,0,0,0.00,32.21,0.0,0.0,0.0,PACOCA DACOL.ROLHA LIG.170G,NaN,CX,17049090,17.001.02,4330736000189,1937635001316,NaN,0,entrada,43201204330736000189550010004809641406923451-15.0,43201204330736000189550010004809641406923451-15.0

In [89]:
tabela_2 = tabela_2[tabela_2.groupby('COD_ITEM')['IND_OPER'].transform(lambda x: not (x.nunique() == 1 and x.iloc[0] == 0))]
tabela_2[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'IND_OPER', 'SUB_TIPO', 'QTD_CAT', 'Valor ICMS Operação',
                        'CST', 'ALIQUOTA', 'FONTE']]

Empty DataFrame
Columns: [CHV_DOC, DATA, CFOP, NUM_ITEM, COD_ITEM, IND_OPER, SUB_TIPO, QTD_CAT, Valor ICMS Operação, CST, ALIQUOTA, FONTE]
Index: []

In [84]:
# tabela_2 = tabela_2.drop('Unnamed: 0', axis=1)
tabela_2 = tabela_2[tabela_2.groupby('COD_ITEM')['IND_OPER'].transform(lambda x: not (x.nunique() == 1 and x.iloc[0] == 0))]
tabela_2 = tabela_2.sort_values(by=['COD_ITEM', 'DATA', 'IND_OPER', 'SUB_TIPO'], 
                            ascending=[True, True, True, True]).reset_index().drop('index', axis=1)

tabela_2['QTD_CAT'] = tabela_2['QTD_CAT'].astype(float)

ficha_3 = tabela_2[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'IND_OPER', 'SUB_TIPO', 'QTD_CAT', 'Valor ICMS Operação',
                        'CST', 'ALIQUOTA', 'FONTE']]

query = 'SELECT * FROM produtos'
produtos = pd.read_sql_query(query, connection)

# Ordenação da tabela de acordo com os critérios definidos
ficha_3['DATA'] = pd.to_datetime(ficha_3['DATA'], format='%Y-%m-%d')
ficha_3 = ficha_3.sort_values(by=['COD_ITEM', 'DATA', 'IND_OPER', 'SUB_TIPO'], 
                            ascending=[True, True, True, True])

ficha_3['ICMS_TOT'] = tabela_2['ICMS_TOT'].astype(float)
ficha_3['ICMS_TOT_SAIDA'] = tabela_2['ICMS_TOT_SAIDA'].astype(float)

ficha_3['VALOR'] = tabela_2['VALOR']

ficha_3 = ficha_3.merge(produtos[['codigo_produto', 'mva_antes']], 
                    left_on='COD_ITEM',
                    right_on='codigo_produto',
                    how='left')
ficha_3 = ficha_3.drop('codigo_produto', axis=1).rename(columns={'mva_antes': 'MVA'})

ficha_3['VALOR'] = ficha_3['VALOR'].astype(str).replace('-', np.nan).astype(float)
ficha_3['ALIQUOTA'] = ficha_3['ALIQUOTA'].astype(str).replace('-', np.nan).astype(float)
ficha_3['MVA'] = ficha_3['MVA'].astype(str).replace('-', np.nan).replace('None', np.nan).astype(float)

cond_1 = ((ficha_3['CST'].astype(float) == 60) & ((ficha_3['ICMS_TOT'] == 0) | (ficha_3['ICMS_TOT'].isnull())))
cond_2 = ((ficha_3['CFOP'].isin([1403, 1409, 1411, 1949, 2403, 2411])) & ((ficha_3['ICMS_TOT'] == 0) | (ficha_3['ICMS_TOT'].isnull())))

ficha_3['ICMS_TOT'] = np.where(cond_1 | cond_2 , 
                            (ficha_3['VALOR'] * (ficha_3['ALIQUOTA'] / 100)) * (ficha_3['MVA'] + 1),
                            ficha_3['ICMS_TOT'])

ficha_3['ICMS_TOT'] = np.where((ficha_3['CFOP'].astype(float).isin([1102, 1202, 2102, 2202])) | (ficha_3['IND_OPER'] == 1),
                                np.nan,
                                ficha_3['ICMS_TOT'])

# ficha_3['ICMS_TOT_SAIDA'] = np.where((ficha_3['IND_OPER'] == 1) & (),
#                                      (ficha_3['VALOR'] * (ficha_3['ALIQUOTA'] / 100)) * (ficha_3['MVA'] + 1),
#                                      np.nan)

cond_1 = ((ficha_3['CST'].astype(float) == 60) & ((ficha_3['Valor ICMS Operação'] == 0) | (ficha_3['Valor ICMS Operação'].isnull())))
cond_2 = ((ficha_3['CFOP'].isin([1403, 1409, 1411, 1949, 2403, 2411])) & ((ficha_3['Valor ICMS Operação'] == 0) | (ficha_3['Valor ICMS Operação'].isnull())))

ficha_3['Valor ICMS Operação'] = np.where(cond_1 | cond_2,
                                        (ficha_3['ALIQUOTA'].astype(float)/ 100) * ficha_3['VALOR'].astype(float),
                                        ficha_3['Valor ICMS Operação'])

ficha_3['Valor ICMS Operação'] = np.where((ficha_3['CFOP'].astype(float).isin([1102, 2102])) | ((ficha_3['CFOP'].astype(float).isin([1202, 2202])) & (ficha_3['CST'] != 60)),
                                np.nan,
                                ficha_3['Valor ICMS Operação'])

data = ficha_3[['COD_ITEM', 'DATA', 'QTD_CAT', 'IND_OPER', 'CFOP']]

# # Transformação da coluna 'DATA' para o tipo correto
# data['DATA'] = pd.to_datetime(data['DATA'], format='%Y-%m-%d')

# # Ordenação do dataset para cálculo correto do ICMS inicial

# data['IND_OPER'] = data['IND_OPER'].astype(int)
# data = data.sort_values(by=['COD_ITEM','DATA', 'IND_OPER'], ascending=[True, True, True])

# # Cáculo dos saldos das operações para definição da Quantidade Inicial
# data['OPER'] = np.where(data['IND_OPER'] == 0, data['QTD_CAT'], -data['QTD_CAT'])
# data['SALDO'] = data.groupby('COD_ITEM')['OPER'].cumsum()

# # Criação da coluna para as informações da Quantidade Inicial

# min_saldo = data.groupby('COD_ITEM')['SALDO'].transform('min')

# # Set 'QTD_INI' to the minimum 'SALDO' value if it's less than or equal to 0,
# # otherwise set it to 0
# data['QTD_INI'] = np.where(min_saldo <= 0, min_saldo.abs(), 0)

# # Get the first rows within each group
# first_rows = data.groupby('COD_ITEM').head(1)

# # Set 'QTD_INI' to NaN for all rows except the last rows within each group
# data['QTD_INI'] = np.where(data.index.isin(first_rows.index), data['QTD_INI'], np.nan)

# # Update 'QTD_INI' with calculated values for the last rows
# data.loc[first_rows.index, 'QTD_INI'] = first_rows['QTD_INI']

# # Cálculo do ICMS inicial 

# data['SUB_TIPO'] = tabela_2['SUB_TIPO']
# data['ICMS_TOT_0'] = ficha_3['ICMS_TOT']
# data['CST'] = ficha_3['CST']
# data['Valor ICMS Operação'] = ficha_3['Valor ICMS Operação'].astype(float)
# data['VALOR_UNIT'] = np.where(data['IND_OPER'] == 0,
#                                 data['ICMS_TOT_0'].fillna(0) / data['QTD_CAT'],
#                                 np.nan)
# data['VALOR_OP_UNIT'] = np.where(data['IND_OPER'] == 0,
#                                 data['Valor ICMS Operação'].fillna(0) / data['QTD_CAT'],
#                                 np.nan)
data

C:\Users\vinic\AppData\Local\Temp\ipykernel_27576\2104677370.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  produtos = pd.read_sql_query(query, connection)

Empty DataFrame
Columns: [COD_ITEM, DATA, QTD_CAT, IND_OPER, CFOP]
Index: []

In [81]:
data['ICMS_INI'] = None
data['ICMS_OP_INI'] = None

# Iterar sobre cada valor único de 'COD_ITEM'
for cod in data['COD_ITEM'].unique():
    # Filtrar todas as linhas para o 'COD_ITEM' atual
    df_cod = data[data['COD_ITEM'] == cod]
    
    # Identificar a primeira linha dentre todas do 'COD_ITEM'
    idx_first = df_cod.index[0]

    # Identificar a primeira linha onde 'IND_OPER' == 0
    df_ind_oper_0 = df_cod[df_cod['IND_OPER'] == 0]
    if not df_ind_oper_0.empty:
        idx_oper_0 = df_ind_oper_0.index[0]

        # Fazer os cálculos e salvar os valores na primeira linha do 'COD_ITEM'
        data.at[idx_first, 'ICMS_INI'] = data.at[idx_oper_0, 'VALOR_UNIT'] * data.at[idx_first, 'QTD_INI']
        data.at[idx_first, 'ICMS_OP_INI'] = data.at[idx_oper_0, 'VALOR_OP_UNIT'] * data.at[idx_first, 'QTD_INI']

data

Empty DataFrame
Columns: [COD_ITEM, DATA, QTD_CAT, IND_OPER, CFOP, OPER, SALDO, QTD_INI, SUB_TIPO, ICMS_TOT_0, CST, Valor ICMS Operação, VALOR_UNIT, VALOR_OP_UNIT, ICMS_INI, ICMS_OP_INI]
Index: []

In [43]:
tabela_2 = tabela_2[tabela_2['COD_ITEM'] == '0JV2S2W01004']

produtos_somente_saida = tabela_2.groupby('COD_ITEM')['IND_OPER'].all()
produtos_somente_saida = produtos_somente_saida[produtos_somente_saida == True].index
prods_icms_0 = data.drop_duplicates(subset='COD_ITEM', keep='first')[(data['QTD_INI'] != 0) & (((data['ICMS_INI'] == 0) | (data['ICMS_INI'].isnull())) | ((data['ICMS_OP_INI'] == 0) | (data['ICMS_OP_INI'].isnull())))]
for produto in list(produtos_somente_saida) + list(prods_icms_0['COD_ITEM'].unique()):
# for produto in data['COD_ITEM'].unique():
# Executa a consulta para obter os valores mva_antes e mva_depois
    query = f"SELECT mva_antes, mva_depois FROM produtos WHERE codigo_produto = '{produto}'"
    try:
        mva = float(pd.read_sql_query(query, connection).dropna(axis=1).iloc[0,0])
    except:
        mva = 0
    print('MVA: ', mva)
    # Calcula o lucro e a quantidade total
    lucro = sum(ficha_3[(ficha_3['COD_ITEM'] == produto) & (ficha_3['IND_OPER'] == 1)]['ICMS_TOT_SAIDA'].fillna(0))
    tot_qtde = sum(ficha_3[(ficha_3['COD_ITEM'] == produto) & (ficha_3['IND_OPER'] == 1)]['QTD_CAT'])
    aliquota = ficha_3[ficha_3['COD_ITEM'] == produto]['ALIQUOTA'].values[0] / 100

    
    try:
        # Calcula o valor unitário, base ST estimada e ICMS
        valor_unit = (lucro * 0.8) / tot_qtde
        print('Valor unitario: ', valor_unit)
        base_st_estimada = valor_unit + (valor_unit * mva)
        print('Base estimada: ', base_st_estimada)
        icms_op_unit = valor_unit * aliquota
        print('ICMS OP UNIT: ', icms_op_unit)
        icms_suport_unit = base_st_estimada * aliquota
        print('Icms suportado unitario: ', icms_suport_unit)
        icms_inicial = icms_suport_unit * tot_qtde
        print('ICMS Inicial: ', icms_inicial)

    except:
        icms_inicial = 0
        icms_op_unit = 0
        

    # Verifica se o produto está presente no DataFrame 'data'
    produto_idx = data[data['COD_ITEM'] == produto].index

    if not produto_idx.empty:
        # Garante que a coluna 'ICMS_INI' seja do tipo float
        data['ICMS_INI'] = data['ICMS_INI'].astype(float)
        data['ICMS_OP_INI'] = data['ICMS_OP_INI'].astype(float)

        # Atualiza o valor na primeira linha correspondente ao COD_ITEM
        data.loc[produto_idx[0], 'ICMS_INI'] = icms_inicial
        data.loc[produto_idx[0], 'ICMS_OP_INI'] = icms_op_unit * data.loc[produto_idx[0], 'QTD_INI']

# Definição das colunas para cálculo de ressarcimento de acordo com as regras
ficha_3['QTD_INI'] = data['QTD_INI'].astype(float)
ficha_3['ICMS_INI'] = data['ICMS_INI'].astype(float)
ficha_3['ICMS_OP_INI'] = data['ICMS_OP_INI'].astype(float)
ficha_3['ICMS_INI'] = np.where((ficha_3['QTD_INI'] == 0) | (ficha_3['ICMS_INI'].isnull() & ficha_3['QTD_INI'].notnull()),
                                0,
                                ficha_3['ICMS_INI'])

ficha_3 = ficha_3[['CHV_DOC', 'DATA', 'CFOP', 'NUM_ITEM', 'COD_ITEM', 'IND_OPER', 
                    'SUB_TIPO', 'QTD_CAT', 'Valor ICMS Operação','CST', 'QTD_INI','ICMS_INI', 'ICMS_OP_INI',
                    'ALIQUOTA', 'FONTE', 'ICMS_TOT','ICMS_TOT_SAIDA', 'VALOR']]
ficha_3

C:\Users\vinic\AppData\Local\Temp\ipykernel_27576\2872094892.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  prods_icms_0 = data.drop_duplicates(subset='COD_ITEM', keep='first')[(data['QTD_INI'] != 0) & (((data['ICMS_INI'] == 0) | (data['ICMS_INI'].isnull())) | ((data['ICMS_OP_INI'] == 0) | (data['ICMS_OP_INI'].isnull())))]

,CHV_DOC,DATA,CFOP,NUM_ITEM,COD_ITEM,IND_OPER,SUB_TIPO,QTD_CAT,Valor ICMS Operação,CST,QTD_INI,ICMS_INI,ICMS_OP_INI,ALIQUOTA,FONTE,ICMS_TOT,ICMS_TOT_SAIDA,VALOR
0,35201262461140001196550550040688761224177650,2020-12-09,1403,17.0,1000005466,0,1,5.0,37.91,70,0.0,0.0,0.0,18.0,entrada,86.45,NaN,315.90
1,35201262461140001196550550040735661859130382,2020-12-16,1403,18.0,1000005466,0,1,3.0,22.75,70,NaN,NaN,NaN,18.0,entrada,51.88,NaN,189.54
2,35201262461140001196550550040688761224177650,2020-12-09,1403,10.0,1000005649,0,1,8.0,44.82,70,0.0,0.0,0.0,18.0,entrada,102.21,NaN,373.44
3,35201262461140001196550550040735661859130382,2020-12-16,1403,9.0,1000005649,0,1,10.0,56.02,70,NaN,NaN,NaN,18.0,entrada,127.75,NaN,466.80
4,35201262461140001196550550040780641857923467,2020-12-23,1403,4.0,1000005649,0,1,6.0,33.61,70,NaN,NaN,NaN,18.0,entrada,76.65,NaN,280.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,43201202160490000119550010002993901835769787,2020-12-23,2403,11.0,82698,0,1,3.0,57.39,10,NaN,NaN,NaN,18.0,entrada,124.14,NaN,478.23
795,43201202160490000119550010002998761517658637,2020-12-30,2403,12.0,82698,0,1,2.0,38.26,10,NaN,NaN,NaN,18.0,entrada,82.76,NaN,318.82
796,43201202160490000119550010002989011152890675,2020-12-17,2403,15.0,82700,0,1,2.0,34.41,10,0.0,0.0,0.0,18.0,entrada,74.44,NaN,286.79
797,43201202160490000119550010002993901835769787,2020-12-23,2403,10.0,82700,0,1,5.0,86.04,10,NaN,NaN,NaN,18.0,entrada,186.11,NaN,716.98
798,43201202160490000119550010002998761517658637,2020-12-30,2403,11.0,82700,0,1,4.0,68.83,10,NaN,NaN,NaN,18.0,entrada,148.89,NaN,573.59

In [52]:
# Inicializa as colunas
ficha_3['valor_op_fixo'] = 0
ficha_3['qtd_fixa'] = 0

# Processamento dos valores fixos acumulados
for cod in ficha_3['COD_ITEM'].unique():
    subset = ficha_3[ficha_3['COD_ITEM'] == cod].copy()

    acum_val = 0
    acum_qtd = 0

    for i, row in subset.iterrows():
        if row['IND_OPER'] == 0:
            ficha_3.loc[i, 'valor_op_fixo'] = acum_val
            ficha_3.loc[i, 'qtd_fixa'] = acum_qtd

            if pd.isna(row['Valor ICMS Operação']):
                acum_val += 0
            else:
                acum_val += row['Valor ICMS Operação']
            acum_qtd += row['QTD_CAT']

# Cálculo do valor médio
valor_medio = []

for cod in ficha_3['COD_ITEM'].unique():
    subset = ficha_3[ficha_3['COD_ITEM'] == cod].copy().reset_index()
    for i, row in subset.iterrows():
        print(i)
        print(row)
        if i == 0:  # Primeira linha
            if row['IND_OPER'] == 0:
                # Calcular com valores acumulados
                if pd.isna(row['Valor ICMS Operação']):
                    num = row['valor_op_fixo'] + 0 + row['ICMS_OP_INI']
                    print('Numerador:', num)
                else:
                    num = row['valor_op_fixo'] + row['Valor ICMS Operação'] + row['ICMS_OP_INI']
                    print('Numerador:', num)
                den = row['qtd_fixa'] + row['QTD_CAT'] + row['QTD_INI']
                print('Denominador:', den)
                valor_medio.append(num / den)
                print('Valor médio:', valor_medio)
            elif row['IND_OPER'] == 1:
                # Calcular com ICMS_OP_INI e QTD_INI
                num = row['ICMS_OP_INI']
                print('Numerador:', num)
                den = row['QTD_INI']
                print('Denominador:', den)
                valor_medio.append(num / den)
                print('Valor médio:', valor_medio)
        else:  # Demais linhas
            if row['IND_OPER'] == 0:
                # Calcular com valores acumulados
                if pd.isna(row['Valor ICMS Operação']):
                    num = row['valor_op_fixo'] + 0 + row['ICMS_OP_INI']
                    print('Numerador:', num)
                else:
                    num = row['valor_op_fixo'] + row['Valor ICMS Operação'] + row['ICMS_OP_INI']
                    print('Numerador:', num)
                den = row['qtd_fixa'] + row['QTD_CAT'] + subset.iloc[0]['QTD_INI']
                print('Denominador:', den)
                valor_medio.append(num / den)
                print('Valor médio:', valor_medio)
            elif row['IND_OPER'] == 1:
                # Para IND_OPER == 1, deixamos como NaN
                valor_medio.append(np.nan)
                print('Valor médio:', valor_medio)
    
print(valor_medio)
# # Adiciona a coluna 'valor_medio' ao DataFrame e preenche valores ausentes
# ficha_3['valor_medio'] = valor_medio
# ficha_3['valor_medio'] = ficha_3['valor_medio'].ffill()

# # Cálculos finais
# ficha_3['COD_LEGAL'] = tabela_2['COD_LEGAL'].astype(float)
# ficha_3['ICMS_EFETIVO_ENTRADA'] = ficha_3['valor_medio'] * ficha_3['QTD_CAT']
# ficha_3['ICMS_EFETIVO_ENTRADA'] = np.where(ficha_3['COD_LEGAL'] > 1,
#                                         ficha_3['ICMS_EFETIVO_ENTRADA'],
#                                         np.nan)
ficha_3

0
index                                                             0
CHV_DOC                35201262461140001196550550040688761224177650
DATA                                            2020-12-09 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       17.0
COD_ITEM                                                 1000005466
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                         5.0
Valor ICMS Operação                                           37.91
CST                                                              70
QTD_INI                                                         0.0
ICMS_INI                                                        0.0
ICMS_OP_INI                                                     0.0
ALIQUOTA                                                       18.0
FONTE                                                       entrada
ICMS_TOT                                                      86.45
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                         315.9
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 0, dtype: object
1
index                                                             1
CHV_DOC                35201262461140001196550550040735661859130382
DATA                                            2020-12-16 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       18.0
COD_ITEM                                                 1000005466
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                         3.0
Valor ICMS Operação                                           22.75
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       18.0
FONTE                                                       entrada
ICMS_TOT                                                      51.88
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                        189.54
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 1, dtype: object
0
index                                                             2
CHV_DOC                35201262461140001196550550040688761224177650
DATA                                            2020-12-09 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       10.0
COD_ITEM                                                 1000005649
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                         8.0
Valor ICMS Operação                                           44.82
CST                                                              70
QTD_INI                                                         0.0
ICMS_INI                                                        0.0
ICMS_OP_INI                                                     0.0
ALIQUOTA                                                       18.0
FONTE                                                       entrada
ICMS_TOT                                                     102.21
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                        373.44
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 0, dtype: object
1
index                                                             3
CHV_DOC                35201262461140001196550550040735661859130382
DATA                                            2020-12-16 00:00:00
CFOP                                                           1403
NUM_ITEM                                                        9.0
COD_ITEM                                                 1000005649
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        10.0
Valor ICMS Operação                                           56.02
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       18.0
FONTE                                                       entrada
ICMS_TOT                                                     127.75
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                         466.8
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 1, dtype: object
2
index                                                             4
CHV_DOC                35201262461140001196550550040780641857923467
DATA                                            2020-12-23 00:00:00
CFOP                                                           1403
NUM_ITEM                                                        4.0
COD_ITEM                                                 1000005649
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                         6.0
Valor ICMS Operação                                           33.61
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       18.0
FONTE                                                       entrada
ICMS_TOT                                                      76.65
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                        280.08
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 2, dtype: object
0
index                                                             5
CHV_DOC                35201262691043002919552000000003511062584651
DATA                                            2020-12-01 00:00:00
CFOP                                                           1403
NUM_ITEM                                                        6.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        10.0
Valor ICMS Operação                                           12.04
CST                                                              70
QTD_INI                                                         0.0
ICMS_INI                                                        0.0
ICMS_OP_INI                                                     0.0
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                      16.41
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                         172.0
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 0, dtype: object
1
index                                                             6
CHV_DOC                35201262691043002919552000000029991334118600
DATA                                            2020-12-05 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       27.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 1, dtype: object
2
index                                                             7
CHV_DOC                35201262691043002919552000000037201888363770
DATA                                            2020-12-07 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       33.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 2, dtype: object
3
index                                                             8
CHV_DOC                35201262691043002919552000000044691554338687
DATA                                            2020-12-08 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       21.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 3, dtype: object
4
index                                                             9
CHV_DOC                35201262691043002919552000000051641796838993
DATA                                            2020-12-09 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       15.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 4, dtype: object
5
index                                                            10
CHV_DOC                35201262691043002919552000000059161182936756
DATA                                            2020-12-10 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       22.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 5, dtype: object
6
index                                                            11
CHV_DOC                35201262691043002919552000000067211560541512
DATA                                            2020-12-11 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       32.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                       7.26
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                          76.2
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 6, dtype: object
7
index                                                            12
CHV_DOC                35201262691043002919552000000073471827298579
DATA                                            2020-12-12 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       30.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        30.0
Valor ICMS Operação                                           10.67
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada
ICMS_TOT                                                      14.54
ICMS_TOT_SAIDA                                                  NaN
VALOR                                                         152.4
valor_op_fixo                                                     0
qtd_fixa                                                          0
Name: 7, dtype: object
8
index                                                            13
CHV_DOC                35201262691043002919552000000079671521693867
DATA                                            2020-12-14 00:00:00
CFOP                                                           1403
NUM_ITEM                                                       36.0
COD_ITEM                                                 1000009004
IND_OPER                                                          0
SUB_TIPO                                                          1
QTD_CAT                                                        15.0
Valor ICMS Operação                                            5.33
CST                                                              70
QTD_INI                                                         NaN
ICMS_INI                                                        NaN
ICMS_OP_INI                                                     NaN
ALIQUOTA                                                       12.0
FONTE                                                       entrada

,CHV_DOC,DATA,CFOP,NUM_ITEM,COD_ITEM,IND_OPER,SUB_TIPO,QTD_CAT,Valor ICMS Operação,CST,QTD_INI,ICMS_INI,ICMS_OP_INI,ALIQUOTA,FONTE,ICMS_TOT,ICMS_TOT_SAIDA,VALOR,valor_op_fixo,qtd_fixa
0,35201262461140001196550550040688761224177650,2020-12-09,1403,17.0,1000005466,0,1,5.0,37.91,70,0.0,0.0,0.0,18.0,entrada,86.45,NaN,315.90,0,0
1,35201262461140001196550550040735661859130382,2020-12-16,1403,18.0,1000005466,0,1,3.0,22.75,70,NaN,NaN,NaN,18.0,entrada,51.88,NaN,189.54,0,0
2,35201262461140001196550550040688761224177650,2020-12-09,1403,10.0,1000005649,0,1,8.0,44.82,70,0.0,0.0,0.0,18.0,entrada,102.21,NaN,373.44,0,0
3,35201262461140001196550550040735661859130382,2020-12-16,1403,9.0,1000005649,0,1,10.0,56.02,70,NaN,NaN,NaN,18.0,entrada,127.75,NaN,466.80,0,0
4,35201262461140001196550550040780641857923467,2020-12-23,1403,4.0,1000005649,0,1,6.0,33.61,70,NaN,NaN,NaN,18.0,entrada,76.65,NaN,280.08,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,43201202160490000119550010002993901835769787,2020-12-23,2403,11.0,82698,0,1,3.0,57.39,10,NaN,NaN,NaN,18.0,entrada,124.14,NaN,478.23,0,0
795,43201202160490000119550010002998761517658637,2020-12-30,2403,12.0,82698,0,1,2.0,38.26,10,NaN,NaN,NaN,18.0,entrada,82.76,NaN,318.82,0,0
796,43201202160490000119550010002989011152890675,2020-12-17,2403,15.0,82700,0,1,2.0,34.41,10,0.0,0.0,0.0,18.0,entrada,74.44,NaN,286.79,0,0
797,43201202160490000119550010002993901835769787,2020-12-23,2403,10.0,82700,0,1,5.0,86.04,10,NaN,NaN,NaN,18.0,entrada,186.11,NaN,716.98,0,0
798,43201202160490000119550010002998761517658637,2020-12-30,2403,11.0,82700,0,1,4.0,68.83,10,NaN,NaN,NaN,18.0,entrada,148.89,NaN,573.59,0,0

In [108]:
ficha_3[ficha_3['COD_ITEM'] == '0JV2S2W01004']

,CHV_DOC,DATA,CFOP,NUM_ITEM,COD_ITEM,IND_OPER,SUB_TIPO,QTD_CAT,Valor ICMS Operação,CST,QTD_INI,ICMS_INI,ICMS_OP_INI,ALIQUOTA,FONTE,ICMS_TOT,ICMS_TOT_SAIDA,VALOR,valor_op_fixo,qtd_fixa,valor_medio,COD_LEGAL,ICMS_EFETIVO_ENTRADA
100272,42200117011376000102550010000522731149876633,2020-01-21,2403,2,0JV2S2W01004,0,1,12.0,12.7500,0.0,3.0,3.1875,3.1875,18.0,entrada,12.75,NaN,318.84,0.00,0.0,1.0625,NaN,NaN
100273,35200165369985000504550060000456721100234481,2020-01-31,6108,28,0JV2S2W01004,1,1,4.0,8.0600,0.0,NaN,NaN,NaN,18.0,saida,NaN,62.027856,201.52,0.00,0.0,1.0625,NaN,NaN
100274,35200265369985000504550060000464811100231594,2020-02-22,5405,2,0JV2S2W01004,1,1,3.0,26.2998,60.0,NaN,NaN,NaN,18.0,saida,NaN,44.972658,146.11,0.00,0.0,1.0625,NaN,NaN
100275,35200665369985000504550060000504531100229316,2020-06-25,5405,6,0JV2S2W01004,1,1,2.0,14.5098,60.0,NaN,NaN,NaN,18.0,saida,NaN,24.811758,80.61,0.00,0.0,1.0625,NaN,NaN
100276,35200665369985000504550060000505761100083958,2020-06-30,5922,2,0JV2S2W01004,1,1,3.0,0.0000,41.0,NaN,NaN,NaN,18.0,saida,NaN,46.520892,151.14,0.00,0.0,1.0625,NaN,NaN
100277,35200765369985000504550060000507651100101485,2020-07-04,5117,2,0JV2S2W01004,1,1,3.0,27.2052,60.0,NaN,NaN,NaN,18.0,saida,NaN,46.520892,151.14,0.00,0.0,1.0625,NaN,NaN
100278,35200906011478000101550010000845291100167183,2020-09-18,1403,4,0JV2S2W01004,0,1,3.0,19.8100,10.0,NaN,NaN,NaN,18.0,entrada,33.87,NaN,110.04,12.75,12.0,1.0625,NaN,NaN
100279,42201117011376000102550010000615661723614342,2020-11-16,2403,3,0JV2S2W01004,0,1,200.0,101.5800,0.0,NaN,NaN,NaN,18.0,entrada,101.58,NaN,2539.60,32.56,15.0,1.0625,NaN,NaN
100280,35201265369985000504550060000569991144644078,2020-12-16,5922,31,0JV2S2W01004,1,1,5.0,0.0000,41.0,NaN,NaN,NaN,18.0,saida,NaN,106.621920,346.40,0.00,0.0,1.0625,NaN,NaN
100281,35201265369985000504550060000570671627052177,2020-12-18,5117,30,0JV2S2W01004,1,1,5.0,62.3520,60.0,NaN,NaN,NaN,18.0,saida,NaN,106.621920,346.40,0.00,0.0,1.0625,NaN,NaN

In [9]:
arquivo_1050 = ler_arquivo_para_dataframe(bucket_name, f'Cat42/{nome_empresa.title()}/1050/1050_{nome_empresa.title()}_{cnpj}_2022_v2.xlsx', file_type='xlsx')

mes_ano = []
for date in arquivo_1050['REF']:
    mes_ano.append(str(date)[5:7] + str(date)[0:4])
    
arquivo_1050['DATA'] = [datetime.strptime(x, '%Y%m').strftime('%m%Y') for x in arquivo_1050['REF'].astype(str)]

Arquivo 'Cat42/Ladakh/1050/1050_Ladakh_07318052000150_2022_v2.xlsx' lido com sucesso!

In [10]:
arquivo_1050['COD_REG'] = ['1050']*(arquivo_1050.shape[0])
arquivo_1050['QTD_INI'] = arquivo_1050['QTD_INI'].apply(lambda x: f"{x:.3f}".replace('.', ','))
# arquivo_1050['ICMS_INI'] = arquivo_1050['ICMS_INI'].astype(float).map(format_number)
arquivo_1050['SALDO_FINAL_MES_QTD'] = arquivo_1050['SALDO_FINAL_MES_QTD'].apply(lambda x: f"{x:.3f}".replace('.', ','))
# arquivo_1050['SALDO_FINAL_MES_ICMS'] = arquivo_1050['SALDO_FINAL_MES_ICMS'].astype(float).map(format_number)

arquivo_1050[(arquivo_1050['REF'] == '202204') & (arquivo_1050['COD_ITEM'] == '91004')]

Empty DataFrame
Columns: [COD_ITEM, REF, QTD_INI, ICMS_INI, SALDO_FINAL_MES_QTD, SALDO_FINAL_MES_ICMS, DATA, COD_REG]
Index: []

In [17]:
arquivo_1050['REF'] = arquivo_1050['REF'].astype(str)
arquivo_1050[(arquivo_1050['REF'] == '202204') & (arquivo_1050['QTD_INI'] == '61,700')]

,COD_ITEM,REF,QTD_INI,ICMS_INI,SALDO_FINAL_MES_QTD,SALDO_FINAL_MES_ICMS,DATA,COD_REG
1111,91004,202204,"61,700",1851.712117,"0,700",21.008079,042022,1050